<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>21&nbsp; Multilevel Network Meta-Regression II: Discrete Outcomes and Approximation Theory – The Mathematics of Indirect Treatment Comparisons</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/part5/22-mlnmr-integration.html" rel="next">
<link href="../../chapters/part5/20-mlnmr-aggregation.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-aafe154f14b83768199b70e6209de778.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part5/20-mlnmr-aggregation.html">Part V: Multilevel Network Meta-Regression</a></li><li class="breadcrumb-item"><a href="../../chapters/part5/21-mlnmr-discrete.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Multilevel Network Meta-Regression II: Discrete Outcomes and Approximation Theory</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">The Mathematics of Indirect Treatment Comparisons</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/choxos/Mathematics-of-ITC" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../notation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notation and Conventions</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Part I: Mathematical Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/01-linear-algebra-i.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Linear Algebra I: Vector Spaces, Linear Maps, and Rank</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/02-linear-algebra-ii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Linear Algebra II: Orthogonality and the Projection Theorem</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/03-linear-algebra-iii.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Linear Algebra III: Spectral Theory and Quadratic Forms</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/04-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Probability and Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/05-inference.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Statistical Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/06-linear-regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Linear Regression from First Principles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/07-glm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Generalized Linear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part1/08-hierarchical-bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Hierarchical Models, Shrinkage, and Bayesian Inference</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Part II: Causal Inference and Estimands</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/09-potential-outcomes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Potential Outcomes and Identification</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/10-adjustment-methods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Adjustment Methods</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/11-effect-modification-collapsibility.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Effect Modification, Interaction, and Collapsibility</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part2/12-transportability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Transportability: The Estimand-Based Theory</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Part III: Meta-Analysis and Network Meta-Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/13-pairwise-meta-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Pairwise Meta-Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/14-bucher.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Indirect Comparison and Bucher’s Theorem</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/15-network-meta-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Network Meta-Analysis: Models and Identifiability</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part3/16-limits-of-nma.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">The Limits of Standard Network Meta-Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Part IV: Population Adjustment: MAIC and STC</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/17-population-adjustment-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Population Adjustment Theory</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/18-maic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Matching-Adjusted Indirect Comparison</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part4/19-stc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Simulated Treatment Comparison</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Part V: Multilevel Network Meta-Regression</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/20-mlnmr-aggregation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Multilevel Network Meta-Regression I: The Aggregation Principle</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/21-mlnmr-discrete.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Multilevel Network Meta-Regression II: Discrete Outcomes and Approximation Theory</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/22-mlnmr-integration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Multilevel Network Meta-Regression III: Numerical Integration Theory</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/23-mlnmr-estimands.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Multilevel Network Meta-Regression IV: Estimands, Identifiability, and Generality</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/24-computation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Bayesian Computation and Diagnostics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/25-general-likelihoods.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">General Likelihoods: Survival and Ordered Categorical Outcomes</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part5/26-ml-umr.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Multilevel Unanchored Meta-Regression</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Part VI: Bias, Comparator Selection, and Rigor</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part6/27-distance-matching.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Aggregate-Level Covariate-Distance Matching</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part6/28-qba.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Quantitative Bias Analysis for Indirect Comparisons</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part6/29-simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Simulation Study Theory</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/part6/30-coq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Machine-Checked Foundations: The Coq Formalization</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../appendices/A-notation-glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Notation Glossary</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../appendices/B-matrix-calculus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Matrix Calculus</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../appendices/C-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Probability Distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../appendices/D-special-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Special Functions for Numerical Integration</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../appendices/E-reference-implementations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Reference Implementations: multinma, mlumr, and uitc</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../appendices/F-solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Solutions to Selected Exercises</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../appendices/G-reading-coq.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">G</span>&nbsp; <span class="chapter-title">Reading the Coq Proofs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-discrete-intro" id="toc-sec-discrete-intro" class="nav-link active" data-scroll-target="#sec-discrete-intro"><span class="header-section-number">21.1</span> Introduction</a></li>
  <li><a href="#sec-discrete-setup" id="toc-sec-discrete-setup" class="nav-link" data-scroll-target="#sec-discrete-setup"><span class="header-section-number">21.2</span> The aggregate count and its two laws</a></li>
  <li><a href="#sec-discrete-roadmap" id="toc-sec-discrete-roadmap" class="nav-link" data-scroll-target="#sec-discrete-roadmap"><span class="header-section-number">21.3</span> A roadmap of the aggregate laws</a></li>
  <li><a href="#sec-poisson-aggregate" id="toc-sec-poisson-aggregate" class="nav-link" data-scroll-target="#sec-poisson-aggregate"><span class="header-section-number">21.4</span> Count outcomes: the Poisson aggregate</a></li>
  <li><a href="#sec-pobin" id="toc-sec-pobin" class="nav-link" data-scroll-target="#sec-pobin"><span class="header-section-number">21.5</span> Binary outcomes: the Poisson binomial and its generating function</a></li>
  <li><a href="#sec-lecam" id="toc-sec-lecam" class="nav-link" data-scroll-target="#sec-lecam"><span class="header-section-number">21.6</span> The Poisson approximation: Le Cam’s total-variation bound</a></li>
  <li><a href="#sec-adjusted" id="toc-sec-adjusted" class="nav-link" data-scroll-target="#sec-adjusted"><span class="header-section-number">21.7</span> The adjusted binomial by moment matching</a></li>
  <li><a href="#sec-discrete-example" id="toc-sec-discrete-example" class="nav-link" data-scroll-target="#sec-discrete-example"><span class="header-section-number">21.8</span> A fully worked aggregate binary likelihood</a></li>
  <li><a href="#sec-discrete-notes" id="toc-sec-discrete-notes" class="nav-link" data-scroll-target="#sec-discrete-notes"><span class="header-section-number">21.9</span> Notes and references</a></li>
  <li><a href="#sec-discrete-exercises" id="toc-sec-discrete-exercises" class="nav-link" data-scroll-target="#sec-discrete-exercises"><span class="header-section-number">21.10</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/part5/20-mlnmr-aggregation.html">Part V: Multilevel Network Meta-Regression</a></li><li class="breadcrumb-item"><a href="../../chapters/part5/21-mlnmr-discrete.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Multilevel Network Meta-Regression II: Discrete Outcomes and Approximation Theory</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Multilevel Network Meta-Regression II: Discrete Outcomes and Approximation Theory</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-discrete-intro" class="level2" data-number="21.1">
<h2 data-number="21.1" class="anchored" data-anchor-id="sec-discrete-intro"><span class="header-section-number">21.1</span> Introduction</h2>
<p>Chapter 20 built the engine of multilevel network meta-regression (ML-NMR) on a single idea, the aggregation principle: to honor an aggregate-data (AgD) study we write the individual-level model (<a href="20-mlnmr-aggregation.html#def-individual-model" class="quarto-xref">Definition&nbsp;<span>20.1</span></a>), push each individual’s linear predictor through the inverse link, and average on the response scale <em>before</em> comparing with the reported summary (<a href="20-mlnmr-aggregation.html#def-aggregate-model" class="quarto-xref">Definition&nbsp;<span>20.2</span></a>, <a href="20-mlnmr-aggregation.html#thm-aggregation" class="quarto-xref">Theorem&nbsp;<span>20.1</span></a>). For a continuous outcome on the identity scale that average is itself the linear predictor evaluated at the covariate mean (<a href="20-mlnmr-aggregation.html#thm-identity-link-exact" class="quarto-xref">Theorem&nbsp;<span>20.3</span></a>), and the aggregate likelihood is an ordinary normal: the arithmetic was gentle because summation and the identity link commute. This chapter takes up the outcomes for which they do not, the counts and the binary events that dominate health-technology assessment, whose aggregate is not a smooth average of a single quantity but a <em>sum</em> of many small, non-identical random contributions, one per patient.</p>
<div id="exm-running-oncology" class="theorem example">
<p><span class="theorem-title"><strong>Example 21.1 (A running example: an oncology responder arm)</strong></span> Throughout this chapter we return to one aggregate-data (AgD) arm from a hypothetical oncology network. Study <span class="math inline">\(AB\)</span> compares drug <span class="math inline">\(A\)</span> against drug <span class="math inline">\(B\)</span>; for the drug-<span class="math inline">\(A\)</span> arm it reports only the <em>number of responders</em> out of the patients treated, a responder being a binary outcome (tumor shrinkage past a fixed threshold). We do not see individual records for this arm, only summary covariates (baseline severity, prior lines of therapy). The ML-NMR model of Chapter 20, fitted to the individual-patient-data (IPD) studies elsewhere in the network, assigns any covariate profile <span class="math inline">\(x\)</span> a response probability <span class="math inline">\(p=\operatorname{expit}(\eta(x))\)</span>, where <span class="math inline">\(\operatorname{expit}(z)=e^{z}/(1+e^{z})\)</span> is the inverse of the logit link (<a href="../part1/07-glm.html#def-link-function" class="quarto-xref">Definition&nbsp;<span>7.2</span></a>).</p>
<p>Two facts make the aggregate awkward. First, patients differ: a frail, heavily pretreated patient may have response probability near <span class="math inline">\(0.1\)</span>, a fit, treatment-naive patient near <span class="math inline">\(0.7\)</span>. Second, we must turn those unequal per-patient probabilities into a single likelihood for the reported total. The naive move is to average the risks to a common <span class="math inline">\(\bar p\)</span> and write <span class="math inline">\(\mathrm{Bin}(n,\bar p)\)</span>; much of this chapter is about what that shortcut gets wrong and how to repair it.</p>
<p>To keep every number checkable by hand, our concrete instance uses five equally weighted covariate profiles with model-predicted response probabilities <span class="math display">\[
\mathbf p=(p_1,\dots,p_5)=(0.1,\ 0.3,\ 0.4,\ 0.5,\ 0.7),
\qquad \bar p=0.4,
\]</span> the vector we carry all the way to the fully worked <a href="#exm-aggregate-binomial" class="quarto-xref">Example&nbsp;<span>21.5</span></a>. These five are <em>profiles that summarize the covariate distribution</em> (the numerical integration nodes of Chapter 22), not necessarily five real patients. Whether we hold them fixed or regard the arm as a random sample from the distribution they summarize is exactly the conditional-versus-marginal choice that organizes everything below. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<p>Two questions organize the chapter. First, what is the exact law of that sum? Second, since the exact law is in general intractable, what tractable distribution approximates it, and how large is the error? The answers split cleanly by outcome type, and the split is itself instructive.</p>
<p>For <strong>count outcomes</strong> the news is good and then subtle. A sum of independent Poisson variables is again Poisson, with rate equal to the sum of the rates, and this holds whether or not the rates are identical (<a href="#lem-poisson-convolution" class="quarto-xref">Lemma&nbsp;<span>21.1</span></a>); the Poisson family is closed under convolution with addition of parameters. So conditional on the patients’ covariates the aggregate count is exactly Poisson (<a href="#thm-poisson-aggregate" class="quarto-xref">Theorem&nbsp;<span>21.1</span></a>), and no approximation is needed at that level. The subtlety is that the covariates are themselves random draws from the study population, so the rate of the conditional Poisson is random, and marginalizing over it yields not a Poisson but a <em>mixed</em> Poisson (a Poisson whose rate is itself random, drawn from a distribution and then averaged out), which carries the same mean and a strictly larger variance. The excess, the overdispersion, is the count-data fingerprint of the within-study covariate variation that ML-NMR exists to respect, and we compute it exactly under Gaussian covariates.</p>
<p>For <strong>binary outcomes</strong> the news is that the obvious guess is wrong. A sum of independent Bernoulli variables with a <em>common</em> success probability is binomial, but a sum of Bernoullis with <em>different</em> success probabilities, exactly the situation when each patient’s event risk <span class="math inline">\(p_i=\operatorname{expit}(\eta(x_i))\)</span> depends on that patient’s covariates, is not binomial. It is the <strong>Poisson binomial</strong> distribution (<a href="../part1/04-probability.html#def-poisson-binomial" class="quarto-xref">Definition&nbsp;<span>4.11</span></a>), whose exact probability mass function is a sum over all <span class="math inline">\(\binom{n}{y}\)</span> subsets of size <span class="math inline">\(y\)</span> and is hopeless to evaluate directly for the sample sizes of a real trial. We derive its structure cleanly through the probability generating function (<a href="#thm-poisson-binomial-pgf" class="quarto-xref">Theorem&nbsp;<span>21.2</span></a>), and then face the practical need for a tractable surrogate. Two classical surrogates answer that need, and they are genuinely different, a point the early ML-NMR literature was careful to separate and we are careful to keep separate here. <strong>Le Cam’s approximation</strong> replaces the Poisson binomial by a Poisson with matched mean and controls the total-variation error by the elegant bound <span class="math inline">\(\sum_i p_i^2\)</span>; we give the full coupling proof (<a href="#thm-le-cam-tv" class="quarto-xref">Theorem&nbsp;<span>21.3</span></a>), one of the few places in Part V where a sharp inequality, rather than a numerical recipe, carries the argument. The <strong>adjusted two-parameter binomial</strong> instead matches the first two moments exactly, producing a binomial whose count is automatically bounded above by its sample size and whose dispersion is correct (<a href="#thm-adjusted-binomial" class="quarto-xref">Theorem&nbsp;<span>21.4</span></a>); it is the surrogate used in practice for binary ML-NMR. We close with a fully worked example that computes an aggregate binary likelihood three ways, by integration to a marginal binomial, by the exact Poisson binomial, and by the adjusted binomial, with the Le Cam Poisson alongside for contrast, and shows by hand which is faithful and which is not.</p>
<p>Throughout, the notation is that of Chapter 20 and of <a href="../../notation.html">Notation</a>: a study indexed <span class="math inline">\(j\)</span>, an arm or treatment indexed <span class="math inline">\(k\)</span>, individuals indexed <span class="math inline">\(i\)</span>, an outcome <span class="math inline">\(Y_{ijk}\)</span> with conditional mean <span class="math inline">\(\theta_{ijk}=g^{-1}(\eta_{jk}(x_{ijk}))\)</span> for the link <span class="math inline">\(g\)</span> (<a href="../part1/07-glm.html#def-link-function" class="quarto-xref">Definition&nbsp;<span>7.2</span></a>) and linear predictor <span class="math inline">\(\eta_{jk}\)</span> of <a href="20-mlnmr-aggregation.html#def-individual-model" class="quarto-xref">Definition&nbsp;<span>20.1</span></a>, and the aggregate mean <span class="math inline">\(\theta_{\bullet jk}=\int_{\mathcal X}g^{-1}(\eta_{jk}(x))\,f_j(x)\,dx\)</span> of <a href="20-mlnmr-aggregation.html#def-aggregate-model" class="quarto-xref">Definition&nbsp;<span>20.2</span></a>. We write <span class="math inline">\(Y_{\bullet jk}=\sum_{i=1}^{n_{jk}}Y_{ijk}\)</span> for the aggregate count over the <span class="math inline">\(n_{jk}\)</span> individuals of arm <span class="math inline">\(k\)</span> in study <span class="math inline">\(j\)</span>, and we drop the study and arm subscripts to <span class="math inline">\(Y_\bullet\)</span>, <span class="math inline">\(n\)</span>, <span class="math inline">\(\theta_\bullet\)</span>, <span class="math inline">\(\eta\)</span>, <span class="math inline">\(\mathbf x\)</span> wherever a single arm is under discussion. This chapter corresponds to results H.8 to H.11 of the proof catalogue.</p>
</section>
<section id="sec-discrete-setup" class="level2" data-number="21.2">
<h2 data-number="21.2" class="anchored" data-anchor-id="sec-discrete-setup"><span class="header-section-number">21.2</span> The aggregate count and its two laws</h2>
<p>Fix a single AgD arm with <span class="math inline">\(n\)</span> individuals. The individual-level model gives, conditional on patient <span class="math inline">\(i\)</span>’s covariate vector <span class="math inline">\(x_i\)</span>, a mean <span class="math inline">\(\theta_i=g^{-1}(\eta(x_i))\)</span> on the outcome scale; the outcomes <span class="math inline">\(Y_i\)</span> are conditionally independent given the covariates. The object the AgD study reports is some function of the aggregate count <span class="math inline">\(Y_\bullet=\sum_i Y_i\)</span>, typically the total number of events <span class="math inline">\(y_\bullet=\sum_i y_i\)</span> out of <span class="math inline">\(n\)</span>, and the aggregate likelihood is the law of <span class="math inline">\(Y_\bullet\)</span> evaluated at <span class="math inline">\(y_\bullet\)</span>. There are two distinct probability laws in play, and conflating them is the principal hazard of this subject, so we isolate them now.</p>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>Conditional versus marginal.</strong> The <strong>conditional law</strong> of <span class="math inline">\(Y_\bullet\)</span> fixes the covariate values <span class="math inline">\(\mathbf x=(x_1,\dots,x_n)\)</span> of the <span class="math inline">\(n\)</span> specific patients and treats only the outcomes as random; it is the law of a sum of independent variables with parameters <span class="math inline">\(\theta_i=g^{-1}(\eta(x_i))\)</span> that differ from patient to patient. The <strong>marginal law</strong> additionally treats each <span class="math inline">\(x_i\)</span> as an independent draw from the study covariate distribution <span class="math inline">\(f_j\)</span> and integrates it out, so that the patients become exchangeable and each single outcome has the aggregate mean <span class="math inline">\(\theta_\bullet=\mathbb{E}_{X\sim f_j}[g^{-1}(\eta(X))]\)</span> of <a href="20-mlnmr-aggregation.html#def-aggregate-model" class="quarto-xref">Definition&nbsp;<span>20.2</span></a>. The marginal law is the mixture of the conditional laws over random covariate configurations. The two have the same mean, <span class="math inline">\(n\theta_\bullet\)</span>, but in general different variances, because randomizing the covariates injects extra variability; the gap between them is the recurring theme of this chapter, appearing as overdispersion for counts (<a href="#thm-poisson-aggregate" class="quarto-xref">Theorem&nbsp;<span>21.1</span></a>) and as the difference between the integrated and adjusted binomials for binary events (<a href="#exm-aggregate-binomial" class="quarto-xref">Example&nbsp;<span>21.5</span></a>). <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<p>Before any machinery, here is the whole distinction in two patients and numbers a reader can check in a minute. It is the seed of the fully worked example at the end of the chapter.</p>
<div id="exm-two-patient-conditional" class="theorem example">
<p><span class="theorem-title"><strong>Example 21.2 (Two patients, two laws, by hand)</strong></span> Take the two extreme profiles of the running example (<a href="#exm-running-oncology" class="quarto-xref">Example&nbsp;<span>21.1</span></a>): a frail patient with response probability <span class="math inline">\(0.1\)</span> and a fit patient with response probability <span class="math inline">\(0.7\)</span>, and suppose the study population is exactly these two profiles in equal proportion (a single binary effect modifier, frail versus fit, prevalence one half). Consider an arm of <span class="math inline">\(n=2\)</span>.</p>
<p><em>Conditional law (profiles held fixed).</em> Fix one patient at each profile. Then <span class="math inline">\(Y_\bullet=Y_1+Y_2\)</span> with <span class="math inline">\(Y_1\sim\mathrm{Ber}(0.1)\)</span> and <span class="math inline">\(Y_2\sim\mathrm{Ber}(0.7)\)</span> independent, so <span class="math display">\[
P(Y_\bullet=0)=0.9\cdot 0.3=0.27,\quad
P(Y_\bullet=1)=0.1\cdot 0.3+0.9\cdot 0.7=0.66,\quad
P(Y_\bullet=2)=0.1\cdot 0.7=0.07,
\]</span> with mean <span class="math inline">\(0.1+0.7=0.8\)</span> and variance <span class="math inline">\(0.1(0.9)+0.7(0.3)=0.30\)</span>.</p>
<p><em>Marginal law (patients drawn at random).</em> Now let each of the two patients be an independent draw from the population, so marginally each is <span class="math inline">\(\mathrm{Ber}(0.4)\)</span> (the average risk) and <span class="math inline">\(Y_\bullet\sim\mathrm{Bin}(2,0.4)\)</span>: <span class="math display">\[
P(Y_\bullet=0)=0.36,\quad P(Y_\bullet=1)=0.48,\quad P(Y_\bullet=2)=0.16,
\]</span> with mean <span class="math inline">\(0.8\)</span> and variance <span class="math inline">\(2(0.4)(0.6)=0.48\)</span>.</p>
<p>The two laws share the mean <span class="math inline">\(0.8\)</span> but differ in variance, <span class="math inline">\(0.30\)</span> against <span class="math inline">\(0.48\)</span>. The extra <span class="math inline">\(0.18\)</span> is the price of randomizing which profile each patient occupies; it equals <span class="math inline">\(n\,s_p^2\)</span> with <span class="math inline">\(s_p^2=\tfrac12\big[(0.1-0.4)^2+(0.7-0.4)^2\big]=0.09\)</span> the variance of the two risks. This single pair of numbers is the entire conditional-versus-marginal theme in miniature, and it returns, with five profiles instead of two, as Step 7 of <a href="#exm-aggregate-binomial" class="quarto-xref">Example&nbsp;<span>21.5</span></a>. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<p>For binary outcomes the marginal law is immediate and is the likelihood ML-NMR uses by default, so we record it before turning to the finer conditional analysis.</p>
<div id="prp-marginal-binomial" class="theorem proposition">
<p><span class="theorem-title"><strong>Proposition 21.1 (The integrated binomial aggregate likelihood)</strong></span> Suppose the individual outcomes are Bernoulli, <span class="math inline">\(Y_i\mid X_i\sim\mathrm{Ber}(g^{-1}(\eta(X_i)))\)</span>, that the covariates <span class="math inline">\(X_1,\dots,X_n\)</span> are independent and identically distributed draws from <span class="math inline">\(f_j\)</span>, and that the outcomes are conditionally independent given the covariates. Then marginally the <span class="math inline">\(Y_i\)</span> are independent and identically distributed <span class="math inline">\(\mathrm{Ber}(\theta_\bullet)\)</span> with <span class="math inline">\(\theta_\bullet\)</span> the aggregate mean of <a href="20-mlnmr-aggregation.html#def-aggregate-model" class="quarto-xref">Definition&nbsp;<span>20.2</span></a>, and the aggregate count is exactly binomial, <span id="eq-integrated-binomial"><span class="math display">\[
Y_\bullet=\sum_{i=1}^n Y_i\ \sim\ \mathrm{Bin}(n,\theta_\bullet),
\qquad
\theta_\bullet=\int_{\mathcal X}g^{-1}(\eta(x))\,f_j(x)\,dx .
\tag{21.1}\]</span></span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>By the tower property, that averaging a conditional probability over the conditioning variable returns the unconditional probability, for each <span class="math inline">\(i\)</span>, <span class="math inline">\(P(Y_i=1)=\mathbb{E}_{X_i}\!\big[P(Y_i=1\mid X_i)\big]=\mathbb{E}_{X_i}\!\big[g^{-1}(\eta(X_i))\big]
=\theta_\bullet\)</span>, the last equality being the definition of the aggregate mean (<a href="20-mlnmr-aggregation.html#def-aggregate-model" class="quarto-xref">Definition&nbsp;<span>20.2</span></a>), which exists by <a href="20-mlnmr-aggregation.html#thm-aggregation" class="quarto-xref">Theorem&nbsp;<span>20.1</span></a>. The pairs <span class="math inline">\((X_i,Y_i)\)</span> are independent across <span class="math inline">\(i\)</span> and identically distributed, so the marginal outcomes <span class="math inline">\(Y_i\)</span> are independent and identically distributed <span class="math inline">\(\mathrm{Ber}(\theta_\bullet)\)</span>; their sum is <span class="math inline">\(\mathrm{Bin}(n,\theta_\bullet)\)</span> by the definition of the binomial as a sum of independent identical Bernoullis (<a href="../part1/04-probability.html#def-binomial" class="quarto-xref">Definition&nbsp;<span>4.9</span></a>). <span class="math inline">\(\square\)</span></p>
</div>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>Reader translation.</strong> Integrating the covariate out first says: treat every future patient from this arm’s target population as carrying the same <em>average</em> response chance <span class="math inline">\(\theta_\bullet\)</span>, even though any one patient’s risk would differ if we saw their covariates. The aggregate count is then an ordinary binomial, exactly as if the arm had run <span class="math inline">\(n\)</span> identical coin flips with success probability <span class="math inline">\(\theta_\bullet\)</span>. Nothing is approximated; the only assumption is that the <span class="math inline">\(n\)</span> patients are an exchangeable sample from <span class="math inline">\(f_j\)</span>. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>Why this is not the end of the story.</strong> Proposition <a href="#prp-marginal-binomial" class="quarto-xref">Proposition&nbsp;<span>21.1</span></a> is exact, requires no approximation, and is the binary aggregate likelihood of the original ML-NMR (<span class="citation" data-cites="phillippo2020mlnmr">Phillippo et al. (<a href="../../references.html#ref-phillippo2020mlnmr" role="doc-biblioref">2020</a>)</span>): compute <span class="math inline">\(\theta_\bullet\)</span> by numerical integration (Chapter 22) and treat the reported events as <span class="math inline">\(\mathrm{Bin}(n,\theta_\bullet)\)</span>. Its one assumption is that the <span class="math inline">\(n\)</span> patients are an exchangeable sample from <span class="math inline">\(f_j\)</span>, so that integrating the covariate out is legitimate before forming the count. The conditional view, which keeps the per-patient risks <span class="math inline">\(p_i\)</span> distinct, is needed for three purposes that occupy the rest of the chapter: to understand the <em>structure</em> of an aggregate event count as a sum of unequal risks (<a href="#thm-poisson-binomial-pgf" class="quarto-xref">Theorem&nbsp;<span>21.2</span></a>); to quantify how a Poisson surrogate for that count behaves (<a href="#thm-le-cam-tv" class="quarto-xref">Theorem&nbsp;<span>21.3</span></a>); and to build the moment-matched binomial that is preferred when one works directly with the integration nodes that represent <span class="math inline">\(f_j\)</span> as a fixed design rather than as a random sample (<a href="#thm-adjusted-binomial" class="quarto-xref">Theorem&nbsp;<span>21.4</span></a>). The gap between the marginal law <a href="#eq-integrated-binomial" class="quarto-xref">Equation&nbsp;<span>21.1</span></a> and the conditional law is exactly the overdispersion we now compute for counts. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
</section>
<section id="sec-discrete-roadmap" class="level2" data-number="21.3">
<h2 data-number="21.3" class="anchored" data-anchor-id="sec-discrete-roadmap"><span class="header-section-number">21.3</span> A roadmap of the aggregate laws</h2>
<p>It is tempting to ask which single likelihood is <em>the</em> binary ML-NMR likelihood. The honest answer is that there are two, and they are not rivals: they are the correct laws for two different ways of representing an AgD study’s covariates. If the arm’s patients are regarded as an exchangeable random sample from the covariate distribution, one integrates the covariate out first and the exact aggregate is the <em>integrated binomial</em> <span class="math inline">\(\mathrm{Bin}(n,\theta_\bullet)\)</span> of <a href="#prp-marginal-binomial" class="quarto-xref">Proposition&nbsp;<span>21.1</span></a>. If instead the covariate distribution is represented by a fixed set of integration nodes carrying distinct risks <span class="math inline">\(p_i\)</span> (the numerical grid of Chapter 22), one conditions on those nodes and the aggregate is a <em>Poisson binomial</em> (<a href="#sec-pobin" class="quarto-xref"><span>Section 21.5</span></a>), for which the <em>adjusted binomial</em> of <a href="#sec-adjusted" class="quarto-xref"><span>Section 21.7</span></a> is the practical two-moment surrogate. The per-node risks <span class="math inline">\(p_i\)</span> are themselves produced by the numerical integration of Chapter 22, which represents the covariate density <span class="math inline">\(f_j\)</span> by nodes drawn through a Gaussian copula <span class="math inline">\(C_\Omega\)</span>; throughout this chapter we take the <span class="math inline">\(p_i\)</span> as given inputs and study only what to do with them.</p>
<p>The count case splits the same way, and <a href="#tbl-aggregate-laws" class="quarto-xref">Table&nbsp;<span>21.1</span></a> collects all five situations. With covariates held fixed the aggregate is exact (Poisson or Poisson binomial); only when the covariates are treated as random does the story change, into overdispersion for counts and into a plain binomial for binary events. The right-hand column points to the section that fills in each row.</p>
<div id="tbl-aggregate-laws" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-aggregate-laws-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;21.1: The five aggregate-likelihood situations of this chapter and the law each one uses. “Covariates fixed” means conditioning on a set of covariate profiles (integration nodes); “covariates random” means treating the patients as an exchangeable sample and integrating the covariate distribution out.
</figcaption>
<div aria-describedby="tbl-aggregate-laws-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Data representation</th>
<th>Exact aggregate law</th>
<th>Tractable directly?</th>
<th>Surrogate used</th>
<th>Surrogate matches</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Count, covariates fixed</td>
<td>Poisson <span class="math inline">\(\mathrm{Poi}(\sum_i W_i)\)</span></td>
<td>yes, exact</td>
<td>none needed</td>
<td>(exact)</td>
</tr>
<tr class="even">
<td>Count, covariates random</td>
<td>mixed Poisson, overdispersed</td>
<td>mean and variance</td>
<td>negative binomial</td>
<td>mean and variance</td>
</tr>
<tr class="odd">
<td>Binary, exchangeable patients</td>
<td><span class="math inline">\(\mathrm{Bin}(n,\theta_\bullet)\)</span></td>
<td>yes, exact</td>
<td>none needed</td>
<td>(exact)</td>
</tr>
<tr class="even">
<td>Binary, fixed nodes</td>
<td>Poisson binomial</td>
<td>exact but intractable</td>
<td>adjusted <span class="math inline">\(\mathrm{Bin}(N^{*},\pi^{*})\)</span></td>
<td>mean and variance</td>
</tr>
<tr class="odd">
<td>Binary, rare events</td>
<td>Poisson binomial</td>
<td>intractable</td>
<td>Le Cam <span class="math inline">\(\mathrm{Poi}(\lambda)\)</span></td>
<td>mean, <span class="math inline">\(+\)</span> TV bound <span class="math inline">\(\sum_i p_i^2\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>A reader who wants only the practical upshot may read <a href="#tbl-aggregate-laws" class="quarto-xref">Table&nbsp;<span>21.1</span></a>, the worked <a href="#exm-aggregate-binomial" class="quarto-xref">Example&nbsp;<span>21.5</span></a>, and the closing remark of <a href="#sec-discrete-example" class="quarto-xref"><span>Section 21.8</span></a>, then skip the proofs on a first pass. The proofs are where the <em>exactness</em> and <em>error</em> claims in the table are earned.</p>
</section>
<section id="sec-poisson-aggregate" class="level2" data-number="21.4">
<h2 data-number="21.4" class="anchored" data-anchor-id="sec-poisson-aggregate"><span class="header-section-number">21.4</span> Count outcomes: the Poisson aggregate</h2>
<p>Count outcomes, modeled with the log link so that <span class="math inline">\(g^{-1}(\eta)=e^{\eta}\)</span>, are the easy case at the conditional level and the instructive case at the marginal level. The conditional ease rests on a closure property of the Poisson family that the binomial family lacks, so we prove it first and in full. The reason to dwell on so elementary a fact is the contrast it draws: the very same closure <em>fails</em> for the Bernoulli, and that single failure is what forces the approximation theory of the second half of the chapter (<a href="#sec-lecam" class="quarto-xref"><span>Section 21.6</span></a>, <a href="#sec-adjusted" class="quarto-xref"><span>Section 21.7</span></a>).</p>
<div id="lem-poisson-convolution" class="theorem lemma">
<p><span class="theorem-title"><strong>Lemma 21.1 (A sum of independent Poissons is Poisson)</strong></span> Let <span class="math inline">\(Y_1,\dots,Y_n\)</span> be independent with <span class="math inline">\(Y_i\sim\mathrm{Poi}(\lambda_i)\)</span>, <span class="math inline">\(\lambda_i&gt;0\)</span>, the rates not necessarily equal. Then <span id="eq-poisson-convolution"><span class="math display">\[
\sum_{i=1}^n Y_i\ \sim\ \mathrm{Poi}\!\Big(\sum_{i=1}^n\lambda_i\Big).
\tag{21.2}\]</span></span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>It suffices to treat <span class="math inline">\(n=2\)</span> and induct, since <span class="math inline">\(Y_1+\cdots+Y_{n}=(Y_1+\cdots+Y_{n-1})+Y_n\)</span> is a sum of two independent Poissons once the inductive hypothesis identifies the first summand as <span class="math inline">\(\mathrm{Poi}(\lambda_1+\cdots+\lambda_{n-1})\)</span>. For <span class="math inline">\(X\sim\mathrm{Poi}(\lambda)\)</span> and <span class="math inline">\(Y\sim\mathrm{Poi}(\mu)\)</span> independent, the convolution formula for the law of a sum of independent nonnegative integer variables gives, for <span class="math inline">\(k=0,1,2,\dots\)</span>, <span class="math display">\[
P(X+Y=k)=\sum_{j=0}^{k}P(X=j)\,P(Y=k-j)
=\sum_{j=0}^{k}e^{-\lambda}\frac{\lambda^{j}}{j!}\,e^{-\mu}\frac{\mu^{k-j}}{(k-j)!}.
\]</span> Factor out <span class="math inline">\(e^{-(\lambda+\mu)}\)</span> and multiply and divide by <span class="math inline">\(k!\)</span>: <span class="math display">\[
P(X+Y=k)=\frac{e^{-(\lambda+\mu)}}{k!}\sum_{j=0}^{k}\binom{k}{j}\lambda^{j}\mu^{k-j}
=\frac{e^{-(\lambda+\mu)}}{k!}\,(\lambda+\mu)^{k},
\]</span> the inner sum being <span class="math inline">\((\lambda+\mu)^k\)</span> by the binomial theorem. This is the mass function of <span class="math inline">\(\mathrm{Poi}(\lambda+\mu)\)</span> (<a href="../part1/04-probability.html#def-poisson" class="quarto-xref">Definition&nbsp;<span>4.10</span></a>), proving the case <span class="math inline">\(n=2\)</span> and, by induction, <a href="#eq-poisson-convolution" class="quarto-xref">Equation&nbsp;<span>21.2</span></a>.</p>
<p>A second proof records the structural reason, and it is this <em>mechanism</em>, not the conclusion, that we reuse: it shows in <a href="#sec-pobin" class="quarto-xref"><span>Section 21.5</span></a> precisely why the Bernoulli analogue breaks. By <a href="../part1/04-probability.html#def-poisson" class="quarto-xref">Definition&nbsp;<span>4.10</span></a> the moment generating function (MGF, <a href="../part1/04-probability.html#def-mgf" class="quarto-xref">Definition&nbsp;<span>4.7</span></a>) of <span class="math inline">\(Y_i\)</span> is <span class="math inline">\(M_{Y_i}(t)=\exp(\lambda_i(e^{t}-1))\)</span>, finite for all <span class="math inline">\(t\)</span>. By the product rule for MGFs of independent sums (<a href="../part1/04-probability.html#thm-mgf-sum" class="quarto-xref">Theorem&nbsp;<span>4.12</span></a>), <span class="math display">\[
M_{\sum_i Y_i}(t)=\prod_{i=1}^n\exp\!\big(\lambda_i(e^{t}-1)\big)
=\exp\!\Big(\Big(\textstyle\sum_i\lambda_i\Big)(e^{t}-1)\Big),
\]</span> which is the MGF of <span class="math inline">\(\mathrm{Poi}(\sum_i\lambda_i)\)</span>; by the uniqueness theorem for moment generating functions (<a href="../part1/04-probability.html#thm-mgf-uniqueness" class="quarto-xref">Theorem&nbsp;<span>4.11</span></a>) the sum has that law. <span class="math inline">\(\square\)</span></p>
</div>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>The asymmetry with the binomial.</strong> In plain terms: pooling several Poisson counts just adds their rates, so there is nothing to approximate for counts, whereas pooling several Bernoulli events does not stay binomial unless the individual risks are equal. Closure under convolution with parameter addition is special. It holds for the Poisson regardless of whether the rates agree, which is why count outcomes give no trouble at the conditional level. It fails for the Bernoulli: a sum of Bernoullis is binomial only when the success probabilities are equal, and otherwise leaves the binomial family entirely for the Poisson binomial of <a href="#sec-pobin" class="quarto-xref"><span>Section 21.5</span></a>. The whole approximation apparatus of this chapter, Le Cam and the adjusted binomial, exists to repair this single missing closure property in the binary case. The MGF proof makes the contrast precise: the Poisson MGF <span class="math inline">\(\exp(\lambda(e^t-1))\)</span> multiplies into the same functional form with <span class="math inline">\(\lambda\)</span> summed, whereas the Bernoulli MGF <span class="math inline">\(1-p+pe^t\)</span> multiplies into <span class="math inline">\(\prod_i(1-p_i+p_ie^t)\)</span>, which is the form of a binomial MGF <span class="math inline">\(((1-p)+pe^t)^n\)</span> only when every <span class="math inline">\(p_i\)</span> is the same <span class="math inline">\(p\)</span>. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<p>We can now state the law of the aggregate count, both conditionally and marginally. Write <span class="math inline">\(\eta(x)=\eta_{jk}(x)\)</span> for the arm’s linear predictor and <span class="math inline">\(W=W(X)=e^{\eta(X)}\)</span> for the random conditional rate of a single individual, so that <span class="math inline">\(\theta_\bullet=\mathbb{E}[W]\)</span> is the aggregate mean of <a href="20-mlnmr-aggregation.html#def-aggregate-model" class="quarto-xref">Definition&nbsp;<span>20.2</span></a> and <span class="math inline">\(\sigma_W^2:=\operatorname{Var}(W)\)</span> measures how much that rate varies across the study population. (Here <span class="math inline">\(W\)</span> is a scalar random rate, not the vector space <span class="math inline">\(W\)</span> of Part I.) The theorem that follows has three layers, worth holding apart: conditional on the patients’ covariates the aggregate count is <em>exactly</em> Poisson; marginally, once the covariates are themselves random, it is an overdispersed <em>mixed</em> Poisson; and under Gaussian covariates the overdispersion collapses to a closed form.</p>
<div id="thm-poisson-aggregate" class="theorem">
<p><span class="theorem-title"><strong>Theorem 21.1 (The Poisson aggregate likelihood and its overdispersion)</strong></span> Let the individual count outcomes satisfy <span class="math inline">\(Y_i\mid X_i\sim\mathrm{Poi}(W_i)\)</span> with <span class="math inline">\(W_i=e^{\eta(X_i)}\)</span>, conditionally independent given the covariates, and let <span class="math inline">\(X_1,\dots,X_n\)</span> be independent and identically distributed draws from <span class="math inline">\(f_j\)</span>.</p>
<ol type="1">
<li><p><em>(Conditional law.)</em> Conditional on the covariate configuration <span class="math inline">\(\mathbf X=(X_1,\dots,X_n)\)</span>, the aggregate count is exactly Poisson, <span id="eq-poisson-agg-conditional"><span class="math display">\[
Y_\bullet=\sum_{i=1}^n Y_i\ \Big|\ \mathbf X\ \sim\ \mathrm{Poi}\!\Big(\sum_{i=1}^n W_i\Big).
\tag{21.3}\]</span></span></p></li>
<li><p><em>(Marginal law.)</em> Marginally over the covariates, <span class="math inline">\(Y_\bullet\)</span> has the <strong>mixed Poisson</strong> law <span id="eq-poisson-agg-marginal"><span class="math display">\[
P(Y_\bullet=y)=\mathbb{E}_{\mathbf X}\!\left[e^{-\Lambda}\frac{\Lambda^{y}}{y!}\right],
\qquad \Lambda=\sum_{i=1}^n W_i,
\tag{21.4}\]</span></span> with mean and variance <span id="eq-poisson-agg-moments"><span class="math display">\[
\mathbb{E}[Y_\bullet]=n\theta_\bullet,
\qquad
\operatorname{Var}(Y_\bullet)=n\theta_\bullet+n\sigma_W^2 .
\tag{21.5}\]</span></span> The marginal count is therefore <strong>overdispersed</strong> relative to a Poisson of the same mean, by exactly <span class="math inline">\(n\sigma_W^2\ge 0\)</span>, with equality (a genuine Poisson) if and only if <span class="math inline">\(W\)</span> is degenerate, that is, if and only if the linear predictor <span class="math inline">\(\eta(X)\)</span> is almost surely constant across the population.</p></li>
<li><p><em>(Gaussian covariates.)</em> If in addition <span class="math inline">\(X\sim\mathcal N(\boldsymbol\mu_j,\boldsymbol\Sigma_j)\)</span> and <span class="math inline">\(\eta(x)=\mu+x^\top\boldsymbol\beta_{\mathrm{tot}}\)</span> is affine in <span class="math inline">\(x\)</span> (with <span class="math inline">\(\boldsymbol\beta_{\mathrm{tot}}=\boldsymbol\beta_1+\boldsymbol\beta_{2,k}\)</span> the total covariate slope of <a href="20-mlnmr-aggregation.html#def-individual-model" class="quarto-xref">Definition&nbsp;<span>20.1</span></a>, the prognostic slopes <span class="math inline">\(\boldsymbol\beta_1\)</span> plus this arm’s effect-modifier interactions <span class="math inline">\(\boldsymbol\beta_{2,k}\)</span>), then the relative overdispersion has the closed form <span id="eq-poisson-agg-overdisp"><span class="math display">\[
\frac{\sigma_W^2}{\theta_\bullet^2}
=\exp\!\big(\boldsymbol\beta_{\mathrm{tot}}^\top\boldsymbol\Sigma_j\boldsymbol\beta_{\mathrm{tot}}\big)-1 .
\tag{21.6}\]</span></span></p></li>
</ol>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span><em>Part 1.</em> Conditional on <span class="math inline">\(\mathbf X\)</span>, the rates <span class="math inline">\(W_i=e^{\eta(X_i)}\)</span> are fixed positive numbers and the <span class="math inline">\(Y_i\)</span> are independent <span class="math inline">\(\mathrm{Poi}(W_i)\)</span>; <a href="#lem-poisson-convolution" class="quarto-xref">Lemma&nbsp;<span>21.1</span></a> gives <span class="math inline">\(Y_\bullet\mid\mathbf X\sim\mathrm{Poi}(\sum_i W_i)\)</span>, which is <a href="#eq-poisson-agg-conditional" class="quarto-xref">Equation&nbsp;<span>21.3</span></a>.</p>
<p><em>Part 2.</em> The marginal mass function is the expectation of the conditional Poisson mass function over the law of <span class="math inline">\(\mathbf X\)</span>, which is <a href="#eq-poisson-agg-marginal" class="quarto-xref">Equation&nbsp;<span>21.4</span></a>. For the moments, write <span class="math inline">\(\Lambda=\sum_i W_i\)</span> and use the tower property and the conditional Poisson identities <span class="math inline">\(\mathbb{E}[Y_\bullet\mid\mathbf X]=\Lambda\)</span> and <span class="math inline">\(\operatorname{Var}(Y_\bullet\mid\mathbf X)=\Lambda\)</span> (mean equals variance for a Poisson, <a href="../part1/04-probability.html#def-poisson" class="quarto-xref">Definition&nbsp;<span>4.10</span></a>). For the mean, <span class="math display">\[
\mathbb{E}[Y_\bullet]=\mathbb{E}\big[\mathbb{E}[Y_\bullet\mid\mathbf X]\big]=\mathbb{E}[\Lambda]
=\sum_{i=1}^n\mathbb{E}[W_i]=n\theta_\bullet,
\]</span> since each <span class="math inline">\(W_i\)</span> has mean <span class="math inline">\(\theta_\bullet=\mathbb{E}[e^{\eta(X)}]\)</span>. For the variance, the law of total variance, <span class="math display">\[
\operatorname{Var}(Y_\bullet)
=\mathbb{E}\big[\operatorname{Var}(Y_\bullet\mid\mathbf X)\big]
+\operatorname{Var}\big(\mathbb{E}[Y_\bullet\mid\mathbf X]\big)
=\mathbb{E}[\Lambda]+\operatorname{Var}(\Lambda),
\]</span> holds because <span class="math inline">\(\mathbb{E}[Y^2]=\mathbb{E}[\mathbb{E}[Y^2\mid\mathbf X]]
=\mathbb{E}[\operatorname{Var}(Y\mid\mathbf X)+\mathbb{E}[Y\mid\mathbf X]^2]\)</span> and subtracting <span class="math inline">\(\mathbb{E}[Y]^2=\mathbb{E}[\mathbb{E}[Y\mid\mathbf X]]^2\)</span> leaves precisely the two displayed terms. Now <span class="math inline">\(\mathbb{E}[\Lambda]=n\theta_\bullet\)</span> as above, and by independence of the <span class="math inline">\(W_i\)</span>, <span class="math inline">\(\operatorname{Var}(\Lambda)=\sum_i\operatorname{Var}(W_i)=n\sigma_W^2\)</span>. Hence <span class="math inline">\(\operatorname{Var}(Y_\bullet)=n\theta_\bullet+n\sigma_W^2\)</span>, which is <a href="#eq-poisson-agg-moments" class="quarto-xref">Equation&nbsp;<span>21.5</span></a>. The excess over the mean is <span class="math inline">\(n\sigma_W^2\ge 0\)</span>, zero exactly when <span class="math inline">\(\sigma_W^2=\operatorname{Var}(e^{\eta(X)})=0\)</span>, that is when <span class="math inline">\(e^{\eta(X)}\)</span>, equivalently <span class="math inline">\(\eta(X)\)</span>, is almost surely constant.</p>
<p><em>Part 3.</em> Under the stated Gaussian assumption <span class="math inline">\(\eta(X)=\mu+X^\top\boldsymbol\beta_{\mathrm{tot}}\)</span> is an affine function of a normal vector, hence univariate normal: for <span class="math inline">\(X\sim\mathcal N(\boldsymbol\mu_j,
\boldsymbol\Sigma_j)\)</span> the scalar <span class="math inline">\(a+\mathbf b^\top X\)</span> has moment generating function <span class="math inline">\(\mathbb{E}[e^{t(a+\mathbf b^\top X)}]=\exp\!\big(t(a+\mathbf b^\top\boldsymbol\mu_j)
+\tfrac12 t^2\,\mathbf b^\top\boldsymbol\Sigma_j\mathbf b\big)\)</span>, which is the MGF of a univariate normal (<a href="../part1/04-probability.html#def-normal" class="quarto-xref">Definition&nbsp;<span>4.12</span></a>), so <span class="math inline">\(\eta(X)\sim\mathcal N(m,s^2)\)</span> with <span class="math inline">\(m=\mu+\boldsymbol\mu_j^\top\boldsymbol\beta_{\mathrm{tot}}\)</span> and <span class="math inline">\(s^2=\boldsymbol\beta_{\mathrm{tot}}^\top\boldsymbol\Sigma_j\boldsymbol\beta_{\mathrm{tot}}\)</span>. Then <span class="math inline">\(W=e^{\eta(X)}\)</span> is log-normal (a variable whose logarithm is normal), and because <span class="math inline">\(\mathbb{E}[W^{r}]=\mathbb{E}[e^{r\eta(X)}]\)</span> is the normal MGF of <span class="math inline">\(\eta(X)\)</span> read off at <span class="math inline">\(t=r\)</span>, its moments are values of that MGF (<a href="../part1/04-probability.html#def-normal" class="quarto-xref">Definition&nbsp;<span>4.12</span></a>): with <span class="math inline">\(M(t)=e^{mt+s^2t^2/2}\)</span>, <span class="math display">\[
\theta_\bullet=\mathbb{E}[W]=\mathbb{E}[e^{\eta(X)}]=M(1)=e^{m+s^2/2},
\qquad
\mathbb{E}[W^2]=\mathbb{E}[e^{2\eta(X)}]=M(2)=e^{2m+2s^2}.
\]</span> The first identity is the closed form of the aggregate rate under the log link (<a href="20-mlnmr-aggregation.html#thm-log-link-mgf" class="quarto-xref">Theorem&nbsp;<span>20.4</span></a>). Therefore <span class="math display">\[
\sigma_W^2=\mathbb{E}[W^2]-\mathbb{E}[W]^2=e^{2m+2s^2}-e^{2m+s^2}=e^{2m+s^2}\big(e^{s^2}-1\big)
=\theta_\bullet^2\big(e^{s^2}-1\big),
\]</span> using <span class="math inline">\(\theta_\bullet^2=e^{2m+s^2}\)</span>. Dividing by <span class="math inline">\(\theta_\bullet^2\)</span> gives <a href="#eq-poisson-agg-overdisp" class="quarto-xref">Equation&nbsp;<span>21.6</span></a>. <span class="math inline">\(\square\)</span></p>
</div>
<div id="exm-count-overdispersion" class="theorem example">
<p><span class="theorem-title"><strong>Example 21.3 (Overdispersion in a two-profile count arm)</strong></span> A hospitalization-count arm has <span class="math inline">\(n=40\)</span> patients and a single binary effect modifier (say, prior hospitalization: yes or no) with prevalence one half. The log-link linear predictor gives conditional rate <span class="math inline">\(W=1\)</span> event per patient at one profile and <span class="math inline">\(W=3\)</span> at the other, so <span class="math display">\[
\theta_\bullet=\mathbb{E}[W]=\tfrac12(1+3)=2,\qquad
\mathbb{E}[W^2]=\tfrac12(1+9)=5,\qquad
\sigma_W^2=5-2^2=1.
\]</span> By <a href="#eq-poisson-agg-moments" class="quarto-xref">Equation&nbsp;<span>21.5</span></a> the marginal count has mean <span class="math inline">\(n\theta_\bullet=40\cdot 2=80\)</span> and variance <span class="math inline">\(n\theta_\bullet+n\sigma_W^2=80+40=120\)</span>, a dispersion index <span class="math inline">\(120/80=1.5\)</span>. A plain <span class="math inline">\(\mathrm{Poi}(n\theta_\bullet)=\mathrm{Poi}(80)\)</span> would claim variance <span class="math inline">\(80\)</span>; ignoring the overdispersion understates the true variance by <span class="math inline">\(40/120\approx 33\%\)</span>, so it treats the reported count as far more informative than it is, and an AgD arm modeled that way would pull the network estimate too hard. This is the count-data face of the conditional-versus-marginal gap of <a href="#exm-two-patient-conditional" class="quarto-xref">Example&nbsp;<span>21.2</span></a>. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>Reading the overdispersion.</strong> The factor <span class="math inline">\(e^{s^2}-1\)</span> in <a href="#eq-poisson-agg-overdisp" class="quarto-xref">Equation&nbsp;<span>21.6</span></a> is the squared coefficient of variation of the random rate <span class="math inline">\(W\)</span>, and <span class="math inline">\(s^2=\boldsymbol\beta_{\mathrm{tot}}^\top
\boldsymbol\Sigma_j\boldsymbol\beta_{\mathrm{tot}}\)</span> is the variance that the covariates induce in the linear predictor through the prognostic and effect-modifying slopes. When those slopes are small, or the covariate spread <span class="math inline">\(\boldsymbol\Sigma_j\)</span> is small, <span class="math inline">\(s^2\)</span> is near zero and <span class="math inline">\(e^{s^2}-1\approx s^2\)</span> is negligible, so the Poisson approximation to the marginal count is excellent and one may safely use <span class="math inline">\(\mathrm{Poi}(n\theta_\bullet)\)</span> as the aggregate likelihood. For a concrete feel, recall <span class="math inline">\(\theta_\bullet=e^{m+s^2/2}\)</span> from the log-link identity (<a href="20-mlnmr-aggregation.html#thm-log-link-mgf" class="quarto-xref">Theorem&nbsp;<span>20.4</span></a>); if <span class="math inline">\(s^2=\boldsymbol\beta_{\mathrm{tot}}^\top\boldsymbol\Sigma_j
\boldsymbol\beta_{\mathrm{tot}}=0.25\)</span>, the relative overdispersion is <span class="math inline">\(e^{0.25}-1\approx 0.28\)</span>, so the rate’s coefficient of variation is <span class="math inline">\(\sqrt{0.28}\approx 0.53\)</span> and each patient contributes excess count variance <span class="math inline">\(\sigma_W^2\approx 0.28\,\theta_\bullet^2\)</span> beyond the Poisson baseline. When the effect modifiers are strong and dispersed, the overdispersion is real and ignoring it understates the uncertainty of the aggregate count, exactly the ecological-bias phenomenon of <a href="../part3/16-limits-of-nma.html#def-ecological-bias" class="quarto-xref">Definition&nbsp;<span>16.2</span></a> seen now in the second moment rather than the first. The naive claim that the marginalized count is itself Poisson is false in this regime; <a href="#eq-poisson-agg-moments" class="quarto-xref">Equation&nbsp;<span>21.5</span></a> is the correct statement. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>The negative-binomial remedy.</strong> When the overdispersion <span class="math inline">\(n\sigma_W^2\)</span> is not negligible, a Poisson aggregate likelihood is misspecified in its variance, and a two-parameter count law is wanted. The natural choice is the negative binomial, which arises precisely as a Gamma-mixed Poisson: if the random rate <span class="math inline">\(\Lambda\)</span> were Gamma distributed, the mixture <a href="#eq-poisson-agg-marginal" class="quarto-xref">Equation&nbsp;<span>21.4</span></a> would be exactly negative binomial. The log-normal mixing implied by Gaussian covariates is not Gamma, so the match is by moments rather than in law, but a negative binomial calibrated to the mean <span class="math inline">\(n\theta_\bullet\)</span> and variance <span class="math inline">\(n\theta_\bullet+n\sigma_W^2\)</span> of <a href="#eq-poisson-agg-moments" class="quarto-xref">Equation&nbsp;<span>21.5</span></a> restores correct dispersion; its extra dispersion parameter plays the role of a study-level random effect on the count scale (<a href="../part1/08-hierarchical-bayes.html#def-random-effects" class="quarto-xref">Definition&nbsp;<span>8.3</span></a>). This is the count-data analogue of the adjusted binomial we build for binary outcomes in <a href="#sec-adjusted" class="quarto-xref"><span>Section 21.7</span></a>, and the two share the same logic: keep the correct first two moments, accept a parametric family that is convenient and respects the natural support. Concretely, in the two-profile arm of <a href="#exm-count-overdispersion" class="quarto-xref">Example&nbsp;<span>21.3</span></a> this means calibrating a negative binomial to mean <span class="math inline">\(80\)</span> and variance <span class="math inline">\(120\)</span> (a dispersion index of <span class="math inline">\(1.5\)</span>); in ML-NMR practice the same excess variance is more often absorbed by a study-level random effect on the log-rate (<a href="../part1/08-hierarchical-bayes.html#def-random-effects" class="quarto-xref">Definition&nbsp;<span>8.3</span></a>), which keeps each covariate profile Poisson while letting the arm as a whole be overdispersed, than by switching count families outright. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<p>This development corresponds to H.8 in the proof catalogue. The catalogue records the corrected statement, that the marginalized aggregate is a mixed Poisson with the overdispersion <a href="#eq-poisson-agg-moments" class="quarto-xref">Equation&nbsp;<span>21.5</span></a>, not a plain Poisson; <a href="#lem-poisson-convolution" class="quarto-xref">Lemma&nbsp;<span>21.1</span></a> is the closure property that makes the <em>conditional</em> aggregate exact.</p>
</section>
<section id="sec-pobin" class="level2" data-number="21.5">
<h2 data-number="21.5" class="anchored" data-anchor-id="sec-pobin"><span class="header-section-number">21.5</span> Binary outcomes: the Poisson binomial and its generating function</h2>
<p>We turn to the binary case, where the aggregate count of events is a sum of independent but non-identical Bernoulli variables. By <a href="#lem-poisson-convolution" class="quarto-xref">Lemma&nbsp;<span>21.1</span></a>’s failing analogue, this sum is not binomial; it is the Poisson binomial of <a href="../part1/04-probability.html#def-poisson-binomial" class="quarto-xref">Definition&nbsp;<span>4.11</span></a>. That definition (Chapter 4) already records the mass function, mean, variance, and MGF of the Poisson binomial. Here we re-derive its structure through the <em>probability generating function</em> (PGF), which is the natural transform for an integer-valued count because it stores the mass function in its Taylor coefficients and turns the convolution of independent counts into a product, exactly as the MGF does on the exponential scale. The PGF is the tool that makes the combinatorial mass function of <a href="../part1/04-probability.html#def-poisson-binomial" class="quarto-xref">Definition&nbsp;<span>4.11</span></a> transparent and that hands us the moments without re-summing the subset expansion.</p>
<div id="def-pgf" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 21.1 (Probability generating function)</strong></span> For a random variable <span class="math inline">\(X\)</span> taking values in <span class="math inline">\(\{0,1,2,\dots\}\)</span>, the <strong>probability generating function</strong> is <span id="eq-pgf-def"><span class="math display">\[
G_X(z):=\mathbb{E}\big[z^{X}\big]=\sum_{k\ge 0}P(X=k)\,z^{k},\qquad |z|\le 1 .
\tag{21.7}\]</span></span> The series converges absolutely for <span class="math inline">\(|z|\le 1\)</span> because the coefficients are a probability distribution. The mass function is recovered by differentiation at the origin, <span class="math inline">\(P(X=k)=G_X^{(k)}(0)/k!\)</span>, and the factorial moments by differentiation at one, <span class="math inline">\(\mathbb{E}[X(X-1)\cdots(X-r+1)]=G_X^{(r)}(1)\)</span> whenever the latter derivative exists. For independent integer-valued <span class="math inline">\(X\perp Y\)</span>, <span class="math inline">\(G_{X+Y}(z)=G_X(z)\,G_Y(z)\)</span>. The PGF and the MGF are related by <span class="math inline">\(G_X(z)=M_X(\log z)\)</span> for <span class="math inline">\(z&gt;0\)</span>. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>Reader translation.</strong> A probability generating function packs an entire count distribution into one polynomial in a bookkeeping variable <span class="math inline">\(z\)</span>: the probability of the count <span class="math inline">\(k\)</span> is simply the coefficient of <span class="math inline">\(z^{k}\)</span>. Its usefulness is that <em>multiplying</em> two such polynomials corresponds to <em>adding</em> two independent counts, so a sum of many simple Bernoulli pieces becomes a product of many simple linear factors that we can expand. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<p>The recovery and product properties asserted in <a href="#def-pgf" class="quarto-xref">Definition&nbsp;<span>21.1</span></a> are standard and elementary: term-by-term differentiation of the power series <a href="#eq-pgf-def" class="quarto-xref">Equation&nbsp;<span>21.7</span></a> is justified within its radius of convergence, evaluation at <span class="math inline">\(z=0\)</span> isolates the coefficient <span class="math inline">\(P(X=k)\)</span>, evaluation of the <span class="math inline">\(r\)</span>-th derivative at <span class="math inline">\(z=1\)</span> gives <span class="math inline">\(\sum_k k(k-1)\cdots(k-r+1)P(X=k)=\mathbb{E}[X(X-1)\cdots(X-r+1)]\)</span>, and the product rule <span class="math inline">\(G_{X+Y}(z)=\mathbb{E}[z^{X+Y}]=\mathbb{E}[z^X]\,\mathbb{E}[z^Y]\)</span> follows from independence exactly as the MGF product rule does (<a href="../part1/04-probability.html#thm-mgf-sum" class="quarto-xref">Theorem&nbsp;<span>4.12</span></a>). We now specialize to the Poisson binomial.</p>
<div id="exm-two-bernoulli-pgf" class="theorem example">
<p><span class="theorem-title"><strong>Example 21.4 (Two unequal risks, expanded by hand)</strong></span> Return to the two extreme profiles of the running example, response probabilities <span class="math inline">\(p_1=0.1\)</span> (frail) and <span class="math inline">\(p_2=0.7\)</span> (fit). The number of responders <span class="math inline">\(Y_\bullet=Y_1+Y_2\)</span> has generating function <span class="math display">\[
G_{Y_\bullet}(z)=(0.9+0.1z)(0.3+0.7z)=0.27+0.66\,z+0.07\,z^2,
\]</span> so, reading off coefficients, <span class="math inline">\(P(Y_\bullet=0)=0.27\)</span>, <span class="math inline">\(P(Y_\bullet=1)=0.66\)</span>, <span class="math inline">\(P(Y_\bullet=2)=0.07\)</span>. The middle coefficient <span class="math inline">\(0.1\cdot 0.3+0.9\cdot 0.7\)</span> is exactly “one patient responds and the other does not, either way around.” This is <em>not</em> <span class="math inline">\(\mathrm{Bin}(2,0.4)\)</span>, which would give <span class="math inline">\(0.36,0.48,0.16\)</span>: both laws have mean <span class="math inline">\(0.8\)</span>, but the unequal risks pile mass onto exactly one responder and thin out the extremes. These are the same conditional two-patient numbers as <a href="#exm-two-patient-conditional" class="quarto-xref">Example&nbsp;<span>21.2</span></a>; the generating function has merely organized the bookkeeping. For five profiles the same kind of product yields the six coefficients computed in <a href="#exm-aggregate-binomial" class="quarto-xref">Example&nbsp;<span>21.5</span></a>, and for a realistic arm of <span class="math inline">\(n=400\)</span> patients the coefficient of <span class="math inline">\(z^{120}\)</span> is a sum of <span class="math inline">\(\binom{400}{120}\)</span> subset products, a number exceeding <span class="math inline">\(10^{100}\)</span>; that is why direct evaluation is hopeless and a tractable surrogate is unavoidable. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<div id="thm-poisson-binomial-pgf" class="theorem">
<p><span class="theorem-title"><strong>Theorem 21.2 (Poisson binomial via the probability generating function)</strong></span> Let <span class="math inline">\(Y_1,\dots,Y_n\)</span> be independent with <span class="math inline">\(Y_i\sim\mathrm{Ber}(p_i)\)</span>, <span class="math inline">\(p_i\in[0,1]\)</span>, and let <span class="math inline">\(Y_\bullet=\sum_{i=1}^n Y_i\sim\mathrm{PoBin}(\mathbf p)\)</span> be their Poisson binomial sum (<a href="../part1/04-probability.html#def-poisson-binomial" class="quarto-xref">Definition&nbsp;<span>4.11</span></a>), <span class="math inline">\(\mathbf p=(p_1,\dots,p_n)\)</span>. Then:</p>
<ol type="1">
<li><p><em>(Generating function.)</em> The probability generating function factors over individuals, <span id="eq-pobin-pgf"><span class="math display">\[
G_{Y_\bullet}(z)=\prod_{i=1}^n\big(1-p_i+p_i z\big).
\tag{21.8}\]</span></span></p></li>
<li><p><em>(Mass function.)</em> The probabilities are the coefficients of this polynomial, <span id="eq-pobin-pmf"><span class="math display">\[
P(Y_\bullet=y)=[z^{y}]\prod_{i=1}^n(1-p_i+p_i z)
=\sum_{\substack{A\subseteq\{1,\dots,n\}\\ |A|=y}}\ \prod_{i\in A}p_i\prod_{i\notin A}(1-p_i),
\qquad y=0,\dots,n,
\tag{21.9}\]</span></span> recovering the subset expansion of <a href="../part1/04-probability.html#def-poisson-binomial" class="quarto-xref">Definition&nbsp;<span>4.11</span></a>.</p></li>
<li><p><em>(Moments.)</em> The mean and variance are <span id="eq-pobin-moments"><span class="math display">\[
\mathbb{E}[Y_\bullet]=\sum_{i=1}^n p_i,
\qquad
\operatorname{Var}(Y_\bullet)=\sum_{i=1}^n p_i(1-p_i).
\tag{21.10}\]</span></span></p></li>
</ol>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span><em>Part 1.</em> Each Bernoulli has PGF <span class="math inline">\(G_{Y_i}(z)=\mathbb{E}[z^{Y_i}]=(1-p_i)z^{0}+p_i z^{1}=1-p_i+p_i z\)</span>. By the product property of <a href="#def-pgf" class="quarto-xref">Definition&nbsp;<span>21.1</span></a>, applied inductively to the mutually independent <span class="math inline">\(Y_i\)</span>, <span class="math inline">\(G_{Y_\bullet}(z)=\prod_{i=1}^n G_{Y_i}(z)=\prod_{i=1}^n(1-p_i+p_i z)\)</span>, which is <a href="#eq-pobin-pgf" class="quarto-xref">Equation&nbsp;<span>21.8</span></a>.</p>
<p><em>Part 2.</em> By <a href="#def-pgf" class="quarto-xref">Definition&nbsp;<span>21.1</span></a> the probability <span class="math inline">\(P(Y_\bullet=y)\)</span> is the coefficient of <span class="math inline">\(z^{y}\)</span> in <span class="math inline">\(G_{Y_\bullet}(z)\)</span>. Expanding the product <a href="#eq-pobin-pgf" class="quarto-xref">Equation&nbsp;<span>21.8</span></a>, a monomial <span class="math inline">\(z^{y}\)</span> is formed by selecting the term <span class="math inline">\(p_i z\)</span> from each factor <span class="math inline">\(i\)</span> in some index set <span class="math inline">\(A\)</span> of size <span class="math inline">\(y\)</span> and the term <span class="math inline">\(1-p_i\)</span> from each factor <span class="math inline">\(i\notin A\)</span>; summing over all such <span class="math inline">\(A\)</span> gives <span class="math inline">\([z^{y}]\prod_i(1-p_i+p_i z)=\sum_{|A|=y}\prod_{i\in A}p_i\prod_{i\notin A}(1-p_i)\)</span>, which is <a href="#eq-pobin-pmf" class="quarto-xref">Equation&nbsp;<span>21.9</span></a> and matches the mass function of <a href="../part1/04-probability.html#def-poisson-binomial" class="quarto-xref">Definition&nbsp;<span>4.11</span></a>.</p>
<p><em>Part 3.</em> Differentiate <a href="#eq-pobin-pgf" class="quarto-xref">Equation&nbsp;<span>21.8</span></a>. By the product rule, <span class="math display">\[
G_{Y_\bullet}'(z)=\sum_{i=1}^n p_i\prod_{\ell\ne i}(1-p_\ell+p_\ell z).
\]</span> At <span class="math inline">\(z=1\)</span> every factor <span class="math inline">\(1-p_\ell+p_\ell\cdot 1=1\)</span>, so <span class="math inline">\(G_{Y_\bullet}'(1)=\sum_i p_i\)</span>, which is the first factorial moment <span class="math inline">\(\mathbb{E}[Y_\bullet]\)</span> by <a href="#def-pgf" class="quarto-xref">Definition&nbsp;<span>21.1</span></a>. Differentiating once more, <span class="math display">\[
G_{Y_\bullet}''(z)=\sum_{i=1}^n p_i\sum_{\ell\ne i}p_\ell\prod_{m\ne i,\ell}(1-p_m+p_m z),
\]</span> and at <span class="math inline">\(z=1\)</span> the surviving products are again <span class="math inline">\(1\)</span>, giving <span class="math inline">\(G_{Y_\bullet}''(1)=\sum_{i\ne\ell}p_i p_\ell=\big(\sum_i p_i\big)^2-\sum_i p_i^2\)</span>, the second factorial moment <span class="math inline">\(\mathbb{E}[Y_\bullet(Y_\bullet-1)]\)</span>. Therefore <span class="math display">\[
\operatorname{Var}(Y_\bullet)=G_{Y_\bullet}''(1)+G_{Y_\bullet}'(1)-\big(G_{Y_\bullet}'(1)\big)^2
=\Big[\big(\textstyle\sum_i p_i\big)^2-\sum_i p_i^2\Big]+\sum_i p_i-\big(\textstyle\sum_i p_i\big)^2
=\sum_i p_i-\sum_i p_i^2,
\]</span> which is <span class="math inline">\(\sum_i p_i(1-p_i)\)</span>, establishing <a href="#eq-pobin-moments" class="quarto-xref">Equation&nbsp;<span>21.10</span></a>. The identity <span class="math inline">\(\operatorname{Var}(X)=G''(1)+G'(1)-G'(1)^2\)</span> used here is the translation of <span class="math inline">\(\operatorname{Var}(X)=\mathbb{E}[X(X-1)]+\mathbb{E}[X]-\mathbb{E}[X]^2\)</span>. <span class="math inline">\(\square\)</span></p>
</div>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>Consistency with Chapter 4 and the binomial special case.</strong> Setting <span class="math inline">\(z=e^{t}\)</span> in <a href="#eq-pobin-pgf" class="quarto-xref">Equation&nbsp;<span>21.8</span></a> recovers the MGF <span class="math inline">\(M_{Y_\bullet}(t)=\prod_i(1-p_i+p_i e^{t})\)</span> recorded in <a href="../part1/04-probability.html#def-poisson-binomial" class="quarto-xref">Definition&nbsp;<span>4.11</span></a>, as the relation <span class="math inline">\(G_X(z)=M_X(\log z)\)</span> of <a href="#def-pgf" class="quarto-xref">Definition&nbsp;<span>21.1</span></a> requires. When all <span class="math inline">\(p_i\)</span> equal a common <span class="math inline">\(p\)</span>, <a href="#eq-pobin-pgf" class="quarto-xref">Equation&nbsp;<span>21.8</span></a> collapses to <span class="math inline">\((1-p+pz)^n\)</span>, the PGF of <span class="math inline">\(\mathrm{Bin}(n,p)\)</span>, whose coefficient of <span class="math inline">\(z^y\)</span> is <span class="math inline">\(\binom{n}{y}p^y(1-p)^{n-y}\)</span>; the Poisson binomial is the exact generalization that permits unequal risks. For fixed mean <span class="math inline">\(\lambda=\sum_i p_i\)</span>, the variance <span class="math inline">\(\lambda-\sum_i p_i^2\)</span> is largest when the <span class="math inline">\(p_i\)</span> are equal, because <span class="math inline">\(\sum_i p_i^2\)</span> is minimized at fixed <span class="math inline">\(\sum_i p_i\)</span> by equal coordinates; spreading the individual risks apart <em>reduces</em> the dispersion of the count, the opposite of the intuition one might carry over from the rates of the Poisson case. The intuition is that a Bernoulli with <span class="math inline">\(p\)</span> near <span class="math inline">\(0\)</span> or <span class="math inline">\(1\)</span> is nearly deterministic (its variance <span class="math inline">\(p(1-p)\)</span> is small), while <span class="math inline">\(p=\tfrac12\)</span> is maximally uncertain; pushing the risks toward the predictable extremes lowers the total count variance. A Poisson rate has no such ceiling, so a more variable rate always <em>inflates</em> the count variance (<a href="#eq-poisson-agg-moments" class="quarto-xref">Equation&nbsp;<span>21.5</span></a>). That is the structural reason counts overdisperse while spread-out binary risks underdisperse. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>Why an approximation is unavoidable.</strong> The mass function <a href="#eq-pobin-pmf" class="quarto-xref">Equation&nbsp;<span>21.9</span></a> has <span class="math inline">\(\binom{n}{y}\)</span> terms, and the full distribution requires expanding a degree-<span class="math inline">\(n\)</span> polynomial; while this can be organized into an <span class="math inline">\(O(n^2)\)</span> recursion or an <span class="math inline">\(O(n\log n)\)</span> discrete Fourier evaluation of <a href="#eq-pobin-pgf" class="quarto-xref">Equation&nbsp;<span>21.8</span></a> on the roots of unity, the result must be recomputed for every candidate value of the parameter vector <span class="math inline">\(\boldsymbol\xi\)</span>, inside every iteration of the Markov chain Monte Carlo sampler of Chapter 24, for every AgD arm. In a network with many arms and thousands of patients this is prohibitive, and worse, it does not compose with the numerical integration over the covariate distribution that ML-NMR also requires (Chapter 22). The practical path is to replace the Poisson binomial by a one- or two-parameter law that captures its salient features cheaply. The next two sections develop the two such laws and, crucially, distinguish what each one guarantees. In inference terms, a faithful surrogate is one that misstates how <em>surprising</em> the reported count is by as little as possible, since that surprise is exactly the AgD arm’s likelihood contribution to the network. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<p>This development corresponds to H.9 in the proof catalogue.</p>
</section>
<section id="sec-lecam" class="level2" data-number="21.6">
<h2 data-number="21.6" class="anchored" data-anchor-id="sec-lecam"><span class="header-section-number">21.6</span> The Poisson approximation: Le Cam’s total-variation bound</h2>
<p>The first surrogate replaces <span class="math inline">\(\mathrm{PoBin}(\mathbf p)\)</span> by a Poisson with the same mean <span class="math inline">\(\lambda=\sum_i p_i\)</span>. Its justification is a sharp bound on the total-variation distance between the two laws, due to <span class="citation" data-cites="lecam1960">Le Cam (<a href="../../references.html#ref-lecam1960" role="doc-biblioref">1960</a>)</span>, which we prove in full by the coupling method. The bound is structural and elegant: the error is at most <span class="math inline">\(\sum_i p_i^2\)</span>, the same quantity that measures how far the individual risks are from zero. We prove a sharp bound, rather than merely assert the approximation, because the bound is a <em>ruler</em>: it says quantitatively when the Poisson shortcut is safe (rare events) and when it silently lies (moderate risks), which is exactly what decides whether an AgD arm’s likelihood can be trusted. We first fix the meaning of total-variation distance and assemble the two elementary facts about it that the proof uses.</p>
<p>The proof has four moving parts, and it helps to see them before they arrive. (i) A <em>definition</em> of total-variation distance, the yardstick for how different two count laws are. (ii) A <em>three-forms lemma</em> rewriting that distance as one half the sum of absolute mass differences, which is what we actually compute. (iii) A <em>coupling inequality</em>: if we can place both laws on one probability space, their distance is at most the chance they disagree. (iv) An <em>exponential inequality</em> <span class="math inline">\(1-e^{-p}\le p\)</span>, the sole analytic input. The plan is then to couple each Bernoulli with a Poisson so they rarely disagree, make the couplings independent, add them up (the Poisson halves sum to a Poisson by <a href="#lem-poisson-convolution" class="quarto-xref">Lemma&nbsp;<span>21.1</span></a>), and bound the total disagreement by a union bound.</p>
<div id="def-total-variation" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 21.2 (Total-variation distance)</strong></span> For probability measures <span class="math inline">\(\mu,\nu\)</span> on a countable set <span class="math inline">\(S\)</span>, the <strong>total-variation distance</strong> is <span id="eq-tv-def"><span class="math display">\[
\|\mu-\nu\|_{\mathrm{TV}}:=\sup_{A\subseteq S}\big|\mu(A)-\nu(A)\big| .
\tag{21.11}\]</span></span> <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>Reader translation.</strong> Total variation is the largest gap, over <em>every</em> possible set of event counts, between the probability the two laws assign to that set. If two aggregate laws are <span class="math inline">\(0.17\)</span> apart in total variation, then for any question of the form “did the arm report a count in this range?” their answers differ by at most <span class="math inline">\(0.17\)</span> in probability. A likelihood built from the wrong law can therefore misstate how surprising an observed count is by up to that much, and that misstatement feeds straight into how strongly the AgD arm pulls the treatment-effect estimate. A total-variation bound is thus a worst-case guarantee on the likelihood error, not an abstract nicety. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<div id="lem-tv-characterization" class="theorem lemma">
<p><span class="theorem-title"><strong>Lemma 21.2 (Three forms of total variation)</strong></span> For probability measures <span class="math inline">\(\mu,\nu\)</span> on a countable set <span class="math inline">\(S\)</span>, <span id="eq-tv-three-forms"><span class="math display">\[
\|\mu-\nu\|_{\mathrm{TV}}
=\tfrac12\sum_{k\in S}\big|\mu(k)-\nu(k)\big|
=1-\sum_{k\in S}\min\big(\mu(k),\nu(k)\big).
\tag{21.12}\]</span></span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Let <span class="math inline">\(A^{+}=\{k:\mu(k)&gt;\nu(k)\}\)</span>. For any <span class="math inline">\(A\subseteq S\)</span>, <span class="math inline">\(\mu(A)-\nu(A)=\sum_{k\in A}(\mu(k)-\nu(k))\le\sum_{k\in A^{+}}(\mu(k)-\nu(k))=\mu(A^{+})-\nu(A^{+})\)</span>, because adding indices outside <span class="math inline">\(A^{+}\)</span> can only subtract nonnegative amounts; symmetrically the most negative value of <span class="math inline">\(\mu(A)-\nu(A)\)</span> is attained at <span class="math inline">\(A^{-}=\{k:\mu(k)&lt;\nu(k)\}\)</span>. Since both <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\nu\)</span> are probability measures, <span class="math inline">\(\sum_k(\mu(k)-\nu(k))=0\)</span>, so the total positive discrepancy equals the total negative discrepancy: <span class="math inline">\(\sum_{k\in A^{+}}(\mu(k)-\nu(k))=\sum_{k\in A^{-}}(\nu(k)-\mu(k))=\tfrac12\sum_k|\mu(k)-\nu(k)|\)</span>. Hence the supremum in <a href="#eq-tv-def" class="quarto-xref">Equation&nbsp;<span>21.11</span></a> equals <span class="math inline">\(\tfrac12\sum_k|\mu(k)-\nu(k)|\)</span>. For the third form, use <span class="math inline">\(\min(a,b)=\tfrac12(a+b-|a-b|)\)</span> to write <span class="math inline">\(\sum_k\min(\mu(k),\nu(k))=\tfrac12\sum_k(\mu(k)+\nu(k))-\tfrac12\sum_k|\mu(k)-\nu(k)|
=1-\|\mu-\nu\|_{\mathrm{TV}}\)</span>. <span class="math inline">\(\square\)</span></p>
</div>
<p>A <strong>coupling</strong> of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\nu\)</span> is a pair of random variables <span class="math inline">\((X,Z)\)</span> on a common probability space with marginal laws <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\nu\)</span>. Couplings turn distances between laws into probabilities of disagreement, by the following one-directional inequality, which is all the proof needs.</p>
<div id="lem-coupling-inequality" class="theorem lemma">
<p><span class="theorem-title"><strong>Lemma 21.3 (The coupling inequality)</strong></span> If <span class="math inline">\((X,Z)\)</span> is any coupling of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\nu\)</span>, then <span id="eq-coupling-ineq"><span class="math display">\[
\|\mu-\nu\|_{\mathrm{TV}}\le P(X\ne Z).
\tag{21.13}\]</span></span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Fix <span class="math inline">\(A\subseteq S\)</span>. Since <span class="math inline">\(X\)</span> has law <span class="math inline">\(\mu\)</span> and <span class="math inline">\(Z\)</span> has law <span class="math inline">\(\nu\)</span>, <span class="math display">\[
\mu(A)-\nu(A)=P(X\in A)-P(Z\in A)
=P(X\in A,\,Z\notin A)-P(Z\in A,\,X\notin A)\le P(X\in A,\,Z\notin A)\le P(X\ne Z),
\]</span> where the second equality splits each event on whether the other variable lands in <span class="math inline">\(A\)</span> and cancels the common term <span class="math inline">\(P(X\in A,Z\in A)\)</span>, and the inequalities drop a nonnegative probability and then enlarge the event <span class="math inline">\(\{X\in A,Z\notin A\}\subseteq\{X\ne Z\}\)</span>. The same bound holds for <span class="math inline">\(\nu(A)-\mu(A)\)</span> by symmetry, so <span class="math inline">\(|\mu(A)-\nu(A)|\le P(X\ne Z)\)</span>; taking the supremum over <span class="math inline">\(A\)</span> gives <a href="#eq-coupling-ineq" class="quarto-xref">Equation&nbsp;<span>21.13</span></a>. <span class="math inline">\(\square\)</span></p>
</div>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>Which way the inequality runs.</strong> A coupling gives an <em>upper</em> bound on total variation, never a lower bound, because we are free to choose the coupling that disagrees as little as possible. (Total variation equals the disagreement of the single best coupling, a converse we do not need here.) So to bound the distance we only have to exhibit <em>one</em> good coupling, which is what the proof does next. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<p>The strategy of Le Cam’s proof is to build, for each individual, a coupling of its Bernoulli law with a Poisson law that disagree only rarely, then to assemble these into a coupling of the whole Poisson binomial with a Poisson by taking the couplings independent across individuals. The independent sum of the Poisson halves is Poisson by <a href="#lem-poisson-convolution" class="quarto-xref">Lemma&nbsp;<span>21.1</span></a>, and the probability that the two sums disagree is bounded by the union of the individual disagreements. The single-pair coupling is explicit, and the only analytic input is the inequality <span class="math inline">\(1-e^{-p}\le p\)</span>, which we record.</p>
<div id="lem-exp-inequality" class="theorem lemma">
<p><span class="theorem-title"><strong>Lemma 21.4 (An elementary exponential inequality)</strong></span> For all <span class="math inline">\(p\ge 0\)</span>, <span class="math inline">\(\,e^{-p}\ge 1-p\)</span>, equivalently <span class="math inline">\(0\le 1-e^{-p}\le p\)</span>.</p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Let <span class="math inline">\(h(p)=e^{-p}-(1-p)\)</span>. Then <span class="math inline">\(h(0)=0\)</span> and <span class="math inline">\(h'(p)=1-e^{-p}\ge 0\)</span> for <span class="math inline">\(p\ge 0\)</span>, so <span class="math inline">\(h\)</span> is nondecreasing and <span class="math inline">\(h(p)\ge h(0)=0\)</span>; thus <span class="math inline">\(e^{-p}\ge 1-p\)</span>. Rearranging gives <span class="math inline">\(1-e^{-p}\le p\)</span>, and <span class="math inline">\(1-e^{-p}\ge 0\)</span> since <span class="math inline">\(e^{-p}\le 1\)</span>. <span class="math inline">\(\square\)</span></p>
</div>
<div id="thm-le-cam-tv" class="theorem">
<p><span class="theorem-title"><strong>Theorem 21.3 (Le Cam’s Poisson approximation to the Poisson binomial)</strong></span> Let <span class="math inline">\(Y_\bullet\sim\mathrm{PoBin}(\mathbf p)\)</span> with <span class="math inline">\(\mathbf p=(p_1,\dots,p_n)\)</span> and <span class="math inline">\(\lambda=\sum_{i=1}^n p_i\)</span>, and let <span class="math inline">\(Z\sim\mathrm{Poi}(\lambda)\)</span>. Then <span id="eq-lecam-bound"><span class="math display">\[
\big\|\mathrm{PoBin}(\mathbf p)-\mathrm{Poi}(\lambda)\big\|_{\mathrm{TV}}\ \le\ \sum_{i=1}^n p_i^2 .
\tag{21.14}\]</span></span></p>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span>Fix an index <span class="math inline">\(i\)</span> and write <span class="math inline">\(p=p_i\)</span>. We construct a coupling <span class="math inline">\((B_i,P_i)\)</span> of <span class="math inline">\(\mathrm{Ber}(p)\)</span> and <span class="math inline">\(\mathrm{Poi}(p)\)</span> with a small probability of disagreement. The idea is to place as much probability as possible on the diagonal <span class="math inline">\(\{B_i=P_i\}\)</span>, so the two agree whenever they can: we match <span class="math inline">\(B_i=P_i=0\)</span> with the largest allowed mass <span class="math inline">\(1-p\)</span>, keep <span class="math inline">\(B_i=P_i=1\)</span> where possible, and dump the leftover Poisson mass (the outcomes <span class="math inline">\(P_i\ge 2\)</span> that a Bernoulli can never reach, plus a sliver forced by the marginals) onto <span class="math inline">\(B_i=1\)</span>. Define the joint law of <span class="math inline">\((B_i,P_i)\)</span> on <span class="math inline">\(\{0,1\}\times\{0,1,2,\dots\}\)</span> by <span id="eq-lecam-pair"><span class="math display">\[
\begin{aligned}
&amp;P(B_i=0,P_i=0)=1-p, \\
&amp;P(B_i=1,P_i=1)=p\,e^{-p}, \\
&amp;P(B_i=1,P_i=0)=e^{-p}-(1-p), \\
&amp;P(B_i=1,P_i=k)=e^{-p}\frac{p^{k}}{k!}\quad (k\ge 2),
\end{aligned}
\tag{21.15}\]</span></span> and all other combinations probability zero. Each entry is nonnegative: the only one in question is <span class="math inline">\(P(B_i=1,P_i=0)=e^{-p}-(1-p)\ge 0\)</span>, which is <a href="#lem-exp-inequality" class="quarto-xref">Lemma&nbsp;<span>21.4</span></a>. We check the marginals. The <span class="math inline">\(P_i\)</span>-marginal at <span class="math inline">\(0\)</span> is <span class="math inline">\((1-p)+(e^{-p}-(1-p))=e^{-p}\)</span>; at <span class="math inline">\(1\)</span> it is <span class="math inline">\(p\,e^{-p}\)</span>; at <span class="math inline">\(k\ge 2\)</span> it is <span class="math inline">\(e^{-p}p^{k}/k!\)</span>; these are exactly the <span class="math inline">\(\mathrm{Poi}(p)\)</span> probabilities (<a href="../part1/04-probability.html#def-poisson" class="quarto-xref">Definition&nbsp;<span>4.10</span></a>). The <span class="math inline">\(B_i\)</span>-marginal at <span class="math inline">\(0\)</span> is <span class="math inline">\(1-p\)</span>, and at <span class="math inline">\(1\)</span> it is <span class="math display">\[
p\,e^{-p}+\big(e^{-p}-(1-p)\big)+\sum_{k\ge 2}e^{-p}\frac{p^{k}}{k!}
=e^{-p}\sum_{k\ge 0}\frac{p^{k}}{k!}-(1-p)=e^{-p}e^{p}-(1-p)=p,
\]</span> so the <span class="math inline">\(B_i\)</span>-marginal is <span class="math inline">\(\mathrm{Ber}(p)\)</span> (<a href="../part1/04-probability.html#def-bernoulli" class="quarto-xref">Definition&nbsp;<span>4.8</span></a>). Thus <a href="#eq-lecam-pair" class="quarto-xref">Equation&nbsp;<span>21.15</span></a> is a valid coupling. Its disagreement probability is the sum of the off-diagonal masses, <span class="math display">\[
P(B_i\ne P_i)=\big(e^{-p}-(1-p)\big)+\sum_{k\ge 2}e^{-p}\frac{p^{k}}{k!}
=\big(e^{-p}-1+p\big)+\big(1-e^{-p}-p\,e^{-p}\big)=p-p\,e^{-p}=p\big(1-e^{-p}\big),
\]</span> where <span class="math inline">\(\sum_{k\ge 2}e^{-p}p^{k}/k!=1-e^{-p}-p\,e^{-p}\)</span> is the Poisson tail beyond <span class="math inline">\(k=1\)</span>. By <a href="#lem-exp-inequality" class="quarto-xref">Lemma&nbsp;<span>21.4</span></a>, <span class="math inline">\(1-e^{-p}\le p\)</span>, so <span id="eq-lecam-pairbound"><span class="math display">\[
P(B_i\ne P_i)=p_i\big(1-e^{-p_i}\big)\le p_i^2 .
\tag{21.16}\]</span></span></p>
<p>For a concrete rate, <span class="math inline">\(p_i=0.2\)</span> gives per-pair disagreement <span class="math inline">\(0.2(1-e^{-0.2})\approx 0.0363\)</span>, just under the bound <span class="math inline">\(p_i^2=0.04\)</span>: the coupled Bernoulli and Poisson agree about <span class="math inline">\(96\%\)</span> of the time.</p>
<p>Now take the <span class="math inline">\(n\)</span> couplings <span class="math inline">\((B_1,P_1),\dots,(B_n,P_n)\)</span> to be independent across <span class="math inline">\(i\)</span>, on a common product probability space. Then <span class="math inline">\(B_1,\dots,B_n\)</span> are independent with <span class="math inline">\(B_i\sim\mathrm{Ber}(p_i)\)</span>, so <span class="math inline">\(Y_\bullet:=\sum_i B_i\sim\mathrm{PoBin}(\mathbf p)\)</span>; and <span class="math inline">\(P_1,\dots,P_n\)</span> are independent with <span class="math inline">\(P_i\sim\mathrm{Poi}(p_i)\)</span>, so by <a href="#lem-poisson-convolution" class="quarto-xref">Lemma&nbsp;<span>21.1</span></a> <span class="math inline">\(Z:=\sum_i P_i\sim\mathrm{Poi}(\sum_i
p_i)=\mathrm{Poi}(\lambda)\)</span>. The pair <span class="math inline">\((Y_\bullet,Z)\)</span> is thus a coupling of <span class="math inline">\(\mathrm{PoBin}(\mathbf p)\)</span> and <span class="math inline">\(\mathrm{Poi}(\lambda)\)</span>. If <span class="math inline">\(B_i=P_i\)</span> for every <span class="math inline">\(i\)</span> then <span class="math inline">\(Y_\bullet=Z\)</span>, so <span class="math inline">\(\{Y_\bullet\ne Z\}\subseteq\bigcup_{i=1}^n\{B_i\ne P_i\}\)</span>, and the union bound with <a href="#eq-lecam-pairbound" class="quarto-xref">Equation&nbsp;<span>21.16</span></a> gives <span class="math display">\[
P(Y_\bullet\ne Z)\le\sum_{i=1}^n P(B_i\ne P_i)\le\sum_{i=1}^n p_i^2 .
\]</span> By the coupling inequality (<a href="#lem-coupling-inequality" class="quarto-xref">Lemma&nbsp;<span>21.3</span></a>) applied to this coupling, <span class="math inline">\(\|\mathrm{PoBin}(\mathbf p)-\mathrm{Poi}(\lambda)\|_{\mathrm{TV}}\le P(Y_\bullet\ne Z)\le\sum_i p_i^2\)</span>, which is <a href="#eq-lecam-bound" class="quarto-xref">Equation&nbsp;<span>21.14</span></a>. <span class="math inline">\(\square\)</span></p>
</div>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>The classical law of small numbers as a special case.</strong> When every <span class="math inline">\(p_i=p\)</span>, the Poisson binomial is <span class="math inline">\(\mathrm{Bin}(n,p)\)</span> and <span class="math inline">\(\lambda=np\)</span>, so <a href="#eq-lecam-bound" class="quarto-xref">Equation&nbsp;<span>21.14</span></a> reads <span class="math inline">\(\|\mathrm{Bin}(n,p)-\mathrm{Poi}(np)\|_{\mathrm{TV}}\le np^2\)</span>. This is the quantitative form of the Poisson limit of the binomial (<a href="../part1/04-probability.html#thm-poisson-limit" class="quarto-xref">Theorem&nbsp;<span>4.13</span></a>): if <span class="math inline">\(p=\lambda/n\)</span>, the bound is <span class="math inline">\(\lambda^2/n\to 0\)</span>, recovering convergence in distribution and adding a rate. Le Cam’s theorem is thus the finite-sample refinement, valid for unequal risks, of the limit theorem proved in Chapter 4. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>Sharpness, refinements, and when the bound is useful.</strong> The bound <a href="#eq-lecam-bound" class="quarto-xref">Equation&nbsp;<span>21.14</span></a> is of the right order: Barbour and Hall (1984) proved the sharper estimate <span class="math inline">\(\|\mathrm{PoBin}(\mathbf p)-\mathrm{Poi}(\lambda)\|_{\mathrm{TV}}\le\min(1,\lambda^{-1})\sum_i p_i^2\)</span> together with a matching lower bound of the same form up to a universal constant, via Stein’s method for Poisson approximation (the operator approach pioneered by Chen in 1975). The factor <span class="math inline">\(\min(1,\lambda^{-1})\)</span> shows that the approximation improves when the events are spread over a large expected count. Physically, events spread over a larger expected count <span class="math inline">\(\lambda\)</span> dilute each event’s share of the error, so the per-event total <span class="math inline">\(\sum_i p_i^2\)</span> is discounted by <span class="math inline">\(\lambda^{-1}\)</span>; for <span class="math inline">\(\lambda&gt;1\)</span> the refined bound reduces to the average risk <span class="math inline">\(\bar p\)</span> itself. The practical lesson for ML-NMR is sobering: with <span class="math inline">\(n=100\)</span> patients at an average risk <span class="math inline">\(\bar p=0.3\)</span>, one has <span class="math inline">\(\sum_i p_i^2\approx n\bar p^2=9\)</span> and even the refined bound <span class="math inline">\(\min(1,1/30)\cdot 9=0.3\)</span> is large, so the Poisson surrogate is a poor approximation to a binary aggregate at the moderate risks typical of clinical events. <a href="#tbl-lecam-regime" class="quarto-xref">Table&nbsp;<span>21.2</span></a> traces the verdict across event rates for <span class="math inline">\(n=100\)</span> patients.</p>
<div id="tbl-lecam-regime" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-lecam-regime-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;21.2: Le Cam and Barbour-Hall total-variation bounds for a binary aggregate of <span class="math inline">\(n=100\)</span> patients at several average risks. The refined bound equals the average risk <span class="math inline">\(\bar p\)</span> in every row with <span class="math inline">\(\lambda&gt;1\)</span>; only rare events (<span class="math inline">\(\bar p\lesssim 0.05\)</span>) put the Poisson surrogate within a usefully small distance of the truth.
</figcaption>
<div aria-describedby="tbl-lecam-regime-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Average risk <span class="math inline">\(\bar p\)</span></th>
<th>Expected count <span class="math inline">\(\lambda=n\bar p\)</span></th>
<th>Le Cam <span class="math inline">\(\approx n\bar p^2\)</span></th>
<th>Barbour-Hall <span class="math inline">\(\approx\min(1,\lambda^{-1})n\bar p^2\)</span></th>
<th>Verdict</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(0.02\)</span></td>
<td><span class="math inline">\(2\)</span></td>
<td><span class="math inline">\(0.04\)</span></td>
<td><span class="math inline">\(0.02\)</span></td>
<td>Poisson excellent</td>
</tr>
<tr class="even">
<td><span class="math inline">\(0.05\)</span></td>
<td><span class="math inline">\(5\)</span></td>
<td><span class="math inline">\(0.25\)</span></td>
<td><span class="math inline">\(0.05\)</span></td>
<td>Poisson usable</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(0.20\)</span></td>
<td><span class="math inline">\(20\)</span></td>
<td><span class="math inline">\(4.0\)</span></td>
<td><span class="math inline">\(0.20\)</span></td>
<td>Poisson poor</td>
</tr>
<tr class="even">
<td><span class="math inline">\(0.50\)</span></td>
<td><span class="math inline">\(50\)</span></td>
<td><span class="math inline">\(25\)</span></td>
<td><span class="math inline">\(0.50\)</span></td>
<td>Poisson useless</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The Poisson approximation earns its place only when both <span class="math inline">\(\lambda\)</span> and the individual <span class="math inline">\(p_i\)</span> are small, the rare-event regime. For the common case of moderate risks and moderate sample sizes, the moment-matched binomial of <a href="#sec-adjusted" class="quarto-xref"><span>Section 21.7</span></a> is the better tool, precisely because it respects the upper bound <span class="math inline">\(Y_\bullet\le n\)</span> that the Poisson, with its unbounded support, violates. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<p>This development corresponds to H.10 in the proof catalogue.</p>
</section>
<section id="sec-adjusted" class="level2" data-number="21.7">
<h2 data-number="21.7" class="anchored" data-anchor-id="sec-adjusted"><span class="header-section-number">21.7</span> The adjusted binomial by moment matching</h2>
<p>The second surrogate keeps the binomial family, with its bounded support <span class="math inline">\(\{0,1,\dots\}\)</span> up to a sample size and its natural fit to event counts, but adjusts its two parameters so that its first two moments agree with those of the Poisson binomial. Unlike Le Cam’s Poisson, this surrogate carries no total-variation guarantee; its justification is exactly that it reproduces the mean and the variance, and nothing more is claimed. We make the construction and its properties precise, and we are scrupulous about what is and is not proved.</p>
<div id="thm-adjusted-binomial" class="theorem">
<p><span class="theorem-title"><strong>Theorem 21.4 (The two-parameter adjusted binomial)</strong></span> Let <span class="math inline">\(Y_\bullet\sim\mathrm{PoBin}(\mathbf p)\)</span> with <span class="math inline">\(\lambda=\sum_{i=1}^n p_i&gt;0\)</span> and <span class="math inline">\(\nu=\sum_{i=1}^n p_i^2\)</span>, so that <span class="math inline">\(\mathbb{E}[Y_\bullet]=\lambda\)</span> and <span class="math inline">\(\operatorname{Var}(Y_\bullet)=\lambda-\nu\)</span> by <a href="#thm-poisson-binomial-pgf" class="quarto-xref">Theorem&nbsp;<span>21.2</span></a>. The unique pair <span class="math inline">\((N^{*},\pi^{*})\)</span> with <span class="math inline">\(N^{*}&gt;0\)</span> and <span class="math inline">\(\pi^{*}\in(0,1)\)</span> for which <span class="math inline">\(\mathrm{Bin}(N^{*},\pi^{*})\)</span> has the same mean and variance, <span id="eq-adjbin-moments"><span class="math display">\[
N^{*}\pi^{*}=\lambda,
\qquad
N^{*}\pi^{*}(1-\pi^{*})=\lambda-\nu,
\tag{21.17}\]</span></span> is <span id="eq-adjbin-solution"><span class="math display">\[
\pi^{*}=\frac{\nu}{\lambda}=\frac{\sum_i p_i^2}{\sum_i p_i},
\qquad
N^{*}=\frac{\lambda^2}{\nu}=\frac{\big(\sum_i p_i\big)^2}{\sum_i p_i^2}.
\tag{21.18}\]</span></span> Moreover:</p>
<ol type="1">
<li><p><span class="math inline">\(\pi^{*}\)</span> is the <span class="math inline">\(p\)</span>-weighted mean of the individual risks, <span class="math inline">\(\pi^{*}=\sum_i(p_i/\lambda)\,p_i\)</span>, and satisfies <span class="math inline">\(\pi^{*}\ge\bar p:=\lambda/n\)</span>, with equality if and only if all <span class="math inline">\(p_i\)</span> are equal.</p></li>
<li><p><span class="math inline">\(N^{*}=\big(\sum_i p_i\big)^2/\sum_i p_i^2\le n\)</span>, with equality if and only if all <span class="math inline">\(p_i\)</span> are equal; this is the effective sample size of the risk vector <span class="math inline">\(\mathbf p\)</span>, the same Cauchy-Schwarz quantity as the effective sample size of Chapter 18 (<a href="../part4/18-maic.html#thm-maic-ess-bound" class="quarto-xref">Theorem&nbsp;<span>18.6</span></a>).</p></li>
</ol>
</div>
<div class="proof">
<p><span class="proof-title"><em>Proof</em>. </span><em>Solving the moment equations.</em> From the first equation in <a href="#eq-adjbin-moments" class="quarto-xref">Equation&nbsp;<span>21.17</span></a>, <span class="math inline">\(N^{*}\pi^{*}=\lambda\)</span>. Expand the second, <span class="math inline">\(N^{*}\pi^{*}(1-\pi^{*})=N^{*}\pi^{*}-N^{*}(\pi^{*})^2=\lambda-N^{*}(\pi^{*})^2\)</span>, and set it equal to <span class="math inline">\(\lambda-\nu\)</span>; the <span class="math inline">\(\lambda\)</span> terms cancel, leaving <span class="math inline">\(N^{*}(\pi^{*})^2=\nu\)</span>. Dividing this by <span class="math inline">\(N^{*}\pi^{*}=\lambda\)</span> gives <span class="math inline">\(\pi^{*}=\nu/\lambda\)</span>, and then <span class="math inline">\(N^{*}=\lambda/\pi^{*}=\lambda^2/\nu\)</span>, which is <a href="#eq-adjbin-solution" class="quarto-xref">Equation&nbsp;<span>21.18</span></a>. These are well defined because <span class="math inline">\(\lambda&gt;0\)</span> and, unless every <span class="math inline">\(p_i=0\)</span>, <span class="math inline">\(\nu=\sum_i p_i^2&gt;0\)</span>. Uniqueness is immediate: the two equations determine <span class="math inline">\(N^{*}(\pi^{*})^2=\nu\)</span> and <span class="math inline">\(N^{*}\pi^{*}=\lambda\)</span>, whose ratio fixes <span class="math inline">\(\pi^{*}\)</span> and hence <span class="math inline">\(N^{*}\)</span>. That <span class="math inline">\(\pi^{*}\in(0,1)\)</span> holds because <span class="math inline">\(0&lt;\nu\le\lambda\)</span> (each <span class="math inline">\(p_i\le 1\)</span> gives <span class="math inline">\(p_i^2\le p_i\)</span>, so <span class="math inline">\(\nu\le\lambda\)</span>, with the bound strict unless every <span class="math inline">\(p_i\in\{0,1\}\)</span>), so <span class="math inline">\(\pi^{*}=\nu/\lambda\in(0,1]\)</span>, and <span class="math inline">\(\pi^{*}&lt;1\)</span> unless the risks are degenerate.</p>
<p><em>Part 1.</em> Writing the weights <span class="math inline">\(\omega_i=p_i/\lambda\)</span>, which are nonnegative and sum to one, <span class="math inline">\(\pi^{*}=\nu/\lambda=\sum_i\omega_i p_i\)</span> is the weighted mean of the <span class="math inline">\(p_i\)</span> with weights proportional to the <span class="math inline">\(p_i\)</span> themselves; larger risks receive larger weight, so the weighted mean exceeds the unweighted mean. Concretely, let <span class="math inline">\(\bar p=\lambda/n\)</span> and let <span class="math inline">\(s_p^2=\tfrac1n\sum_i(p_i-\bar p)^2=\tfrac1n\nu-\bar p^2\)</span> be the population variance of the risks. Then <span class="math display">\[
\pi^{*}=\frac{\nu}{\lambda}=\frac{n(\bar p^2+s_p^2)}{n\bar p}=\bar p+\frac{s_p^2}{\bar p}\ \ge\ \bar p,
\]</span> with equality if and only if <span class="math inline">\(s_p^2=0\)</span>, that is, all <span class="math inline">\(p_i\)</span> equal.</p>
<p><em>Part 2.</em> By the Cauchy-Schwarz inequality applied to the vectors <span class="math inline">\(\mathbf 1=(1,\dots,1)\)</span> and <span class="math inline">\(\mathbf p=(p_1,\dots,p_n)\)</span>, <span class="math display">\[
\lambda^2=\Big(\sum_i 1\cdot p_i\Big)^2\le\Big(\sum_i 1^2\Big)\Big(\sum_i p_i^2\Big)=n\,\nu,
\]</span> so <span class="math inline">\(N^{*}=\lambda^2/\nu\le n\)</span>, with equality if and only if <span class="math inline">\(\mathbf p\)</span> is proportional to <span class="math inline">\(\mathbf 1\)</span>, that is, all <span class="math inline">\(p_i\)</span> equal. The expression <span class="math inline">\(\big(\sum_i p_i\big)^2/\sum_i p_i^2\)</span> is the effective-sample-size functional of Chapter 18 (<a href="../part4/18-maic.html#thm-maic-ess-bound" class="quarto-xref">Theorem&nbsp;<span>18.6</span></a>) evaluated with the <span class="math inline">\(p_i\)</span> in the role of weights; the adjusted binomial’s “sample size” <span class="math inline">\(N^{*}\)</span> is literally the effective number of independent equal-risk trials that the unequal-risk Poisson binomial is worth. <span class="math inline">\(\square\)</span></p>
</div>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>Reader translation.</strong> The adjusted binomial answers the question “which single equal-risk binomial has the same mean and spread as my unequal-risk count?” Its success probability <span class="math inline">\(\pi^{*}=\nu/\lambda\)</span> is a risk-weighted average of the individual risks, so it sits <em>above</em> the plain average <span class="math inline">\(\bar p\)</span> because higher-risk patients count more toward it, and its size <span class="math inline">\(N^{*}=\lambda^2/\nu\)</span> is the <em>effective number of equal-risk trials</em> the arm is worth. Both parameters are chosen so the surrogate reproduces the count’s mean and variance exactly; nothing else is promised. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>Why a weighting quantity reappears here.</strong> It can seem surprising that <span class="math inline">\(N^{*}=(\sum_i p_i)^2/\sum_i p_i^2\)</span> is the same functional as the effective sample size of matching-adjusted indirect comparison (<a href="../part4/18-maic.html#thm-maic-ess-bound" class="quarto-xref">Theorem&nbsp;<span>18.6</span></a>), since one is a <em>likelihood</em> construction and the other a <em>weighting</em> diagnostic. The reason is structural: both are Cauchy-Schwarz answers to “how many equal-information units are these unequal ones worth?” In MAIC the inputs are the weights <span class="math inline">\(w_i\)</span> and the answer is how many equally weighted patients carry the same information; here the inputs are the risks <span class="math inline">\(p_i\)</span> and the answer is how many equal-risk Bernoulli trials carry the same mean and variance. Same inequality, different inputs. To keep the two apart, read <span class="math inline">\(N^{*}\)</span> as the <em>likelihood</em> effective sample size, structurally identical to the <em>weighting</em> effective sample size of Chapter 18 but playing a different role, not the MAIC effective sample size of any particular analysis. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>What is guaranteed, and what is not.</strong> The adjusted binomial <span class="math inline">\(\mathrm{Bin}(N^{*},\pi^{*})\)</span> matches the Poisson binomial’s mean and variance <em>exactly</em>, by construction. It does <strong>not</strong> in general match the third or higher moments, and no total-variation bound of the Le Cam type (<a href="#thm-le-cam-tv" class="quarto-xref">Theorem&nbsp;<span>21.3</span></a>) is asserted or true for it: moment matching is a different and weaker promise than a bound on the distance between laws. The contrast with the Poisson approximation is instructive and the two should never be conflated. The Le Cam Poisson has a total-variation guarantee but the wrong variance (a Poisson has variance equal to its mean <span class="math inline">\(\lambda\)</span>, whereas the Poisson binomial has the smaller variance <span class="math inline">\(\lambda-\nu\)</span>) and unbounded support; the adjusted binomial has the right first two moments and the correct bounded support <span class="math inline">\(\{0,\dots,N^{*}\}\)</span> but no distance guarantee. They serve different regimes: the Poisson when <span class="math inline">\(\lambda\)</span> and the <span class="math inline">\(p_i\)</span> are small, the adjusted binomial when the sample size is moderate and the natural bound <span class="math inline">\(Y_\bullet\le n\)</span> on the count is the feature that matters. In inference terms, choosing the wrong surrogate mis-scales the likelihood: the Le Cam Poisson, with variance <span class="math inline">\(\lambda&gt;\lambda-\nu\)</span>, makes the observed count look <em>less</em> surprising than it is and so lets the arm speak too softly, whereas a correctly moment-matched law reports the right surprise and hence the right weight in the network. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>Non-integer <span class="math inline">\(N^{*}\)</span> and practical use.</strong> The effective sample size <span class="math inline">\(N^{*}=\lambda^2/\nu\)</span> is generally not an integer, so <span class="math inline">\(\mathrm{Bin}(N^{*},\pi^{*})\)</span> is used as a <em>likelihood</em> with a continuous size parameter, its mass function written through Gamma functions, <span class="math inline">\(P(y)=\frac{\Gamma(N^{*}+1)}{\Gamma(y+1)\,\Gamma(N^{*}-y+1)}(\pi^{*})^{y}(1-\pi^{*})^{N^{*}-y}\)</span>, which the Markov chain Monte Carlo sampler of Chapter 24 evaluates without difficulty.</p>
<p>A binomial with a non-integer size such as <span class="math inline">\(\mathrm{Bin}(3.7,0.45)\)</span> looks strange at first sight; the Gamma-function form is exactly the smooth interpolation that makes sense of it, agreeing with the ordinary binomial coefficient whenever <span class="math inline">\(N^{*}\)</span> happens to be a whole number. One caveat deserves flagging. The continuous mass is defined only for <span class="math inline">\(0\le y\le N^{*}\)</span>, and since <span class="math inline">\(N^{*}\le n\)</span> an observed count can in principle exceed <span class="math inline">\(N^{*}\)</span>: in <a href="#exm-aggregate-binomial" class="quarto-xref">Example&nbsp;<span>21.5</span></a> the count <span class="math inline">\(y=5\)</span> is possible under the true law yet falls outside the adjusted binomial’s support <span class="math inline">\(\{0,\dots,N^{*}\}=\{0,\dots,4\}\)</span>. In a real arm the reported total is a fixed number out of the real <span class="math inline">\(n\)</span>, and for the mild risk spreads usual in practice <span class="math inline">\(N^{*}\)</span> sits close to <span class="math inline">\(n\)</span>, so <span class="math inline">\(y\le N^{*}\)</span> holds comfortably; when it does not, the exact integrated binomial <a href="#eq-integrated-binomial" class="quarto-xref">Equation&nbsp;<span>21.1</span></a> (integer <span class="math inline">\(n\)</span>, full support <span class="math inline">\(\{0,\dots,n\}\)</span>) is the safe fallback, which is one reason implementations that anticipate occasional extreme counts prefer it.</p>
<p>This is the adjusted-binomial aggregate likelihood used for binary outcomes in <span class="citation" data-cites="phillippo2020mlnmr">Phillippo et al. (<a href="../../references.html#ref-phillippo2020mlnmr" role="doc-biblioref">2020</a>)</span> and in the thesis <span class="citation" data-cites="phillippo2019thesis">Phillippo (<a href="../../references.html#ref-phillippo2019thesis" role="doc-biblioref">2019</a>)</span> (its psoriasis case study), where the per-node event probabilities produced by the integration pipeline of Chapter 22 are summarized by their two moments <span class="math inline">\(\lambda\)</span> and <span class="math inline">\(\nu\)</span> and fed to <a href="#eq-adjbin-solution" class="quarto-xref">Equation&nbsp;<span>21.18</span></a>. Because <span class="math inline">\(N^{*}\le n\)</span>, the adjusted binomial automatically reports less information than <span class="math inline">\(n\)</span> independent equal-risk trials would, the count-likelihood echo of the effective-sample-size deflation that weighting methods pay (<a href="../part4/18-maic.html#thm-maic-ess-bound" class="quarto-xref">Theorem&nbsp;<span>18.6</span></a>). <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<p>This development corresponds to H.11 in the proof catalogue.</p>
</section>
<section id="sec-discrete-example" class="level2" data-number="21.8">
<h2 data-number="21.8" class="anchored" data-anchor-id="sec-discrete-example"><span class="header-section-number">21.8</span> A fully worked aggregate binary likelihood</h2>
<p>We carry a single AgD arm from covariate-specified individual risks to an aggregate likelihood, computing the latter three ways and laying the Le Cam Poisson alongside for contrast. Every number is exact and checkable by hand. The example is built so that the adjusted binomial has integer parameters, which keeps its mass function elementary, and so that the moment summaries <span class="math inline">\(\lambda\)</span> and <span class="math inline">\(\nu\)</span> come out in round numbers, which makes every law auditable by hand.</p>
<div id="exm-aggregate-binomial" class="theorem example">
<p><span class="theorem-title"><strong>Example 21.5 (An aggregate event count by integration, exactly, and by approximation)</strong></span> An AgD arm reports the number of responders out of <span class="math inline">\(n=5\)</span> patients. The study covariate distribution <span class="math inline">\(f_j\)</span> is represented, through the integration of Chapter 22, by five equally weighted profiles, at which the individual-level model of <a href="20-mlnmr-aggregation.html#def-individual-model" class="quarto-xref">Definition&nbsp;<span>20.1</span></a> gives the response probabilities <span id="eq-ex-pvec"><span class="math display">\[
\mathbf p=(p_1,\dots,p_5)=(0.1,\ 0.3,\ 0.4,\ 0.5,\ 0.7),
\tag{21.19}\]</span></span> with <span class="math inline">\(p_i=\operatorname{expit}(\eta(x_i))\)</span> for the logit link (<a href="../part1/07-glm.html#def-link-function" class="quarto-xref">Definition&nbsp;<span>7.2</span></a>), where <span class="math inline">\(\operatorname{expit}(z)=e^{z}/(1+e^{z})\)</span>. The five profiles span a range of risks, from a low-risk profile at <span class="math inline">\(0.1\)</span> to a high-risk profile at <span class="math inline">\(0.7\)</span>, with average risk <span class="math inline">\(0.4\)</span>.</p>
<p><em>Patients or profiles?</em> The five values above are a numerical summary of the arm’s covariate distribution, the integration nodes of Chapter 22, not necessarily five individual patients. We nonetheless take the reported arm size to be <span class="math inline">\(n=5\)</span> so that every count is checkable by hand; picture a stylized arm in which each profile stands for one patient. The conditional-versus-marginal question is precisely whether we hold these five profiles fixed (the conditional Poisson binomial of route two) or regard the arm as five exchangeable draws from the covariate distribution they summarize (the integrated binomial of route one).</p>
<p><strong>Step 1: the summary moments.</strong> Compute <span class="math display">\[
\lambda=\sum_i p_i=0.1+0.3+0.4+0.5+0.7=2.0,
\qquad
\nu=\sum_i p_i^2=0.01+0.09+0.16+0.25+0.49=1.00 .
\]</span> The aggregate response probability of <a href="20-mlnmr-aggregation.html#def-aggregate-model" class="quarto-xref">Definition&nbsp;<span>20.2</span></a> is the average risk, <span class="math inline">\(\theta_\bullet=\lambda/n=2.0/5=0.4\)</span>.</p>
<p><strong>Step 2: the integrated binomial (route one).</strong> Treating the five patients as an exchangeable sample from <span class="math inline">\(f_j\)</span>, <a href="#prp-marginal-binomial" class="quarto-xref">Proposition&nbsp;<span>21.1</span></a> gives the aggregate count law <span class="math inline">\(\mathrm{Bin}(n,\theta_\bullet)=
\mathrm{Bin}(5,0.4)\)</span> exactly. Its mass function <span class="math inline">\(P(y)=\binom{5}{y}(0.4)^{y}(0.6)^{5-y}\)</span> is <span id="eq-ex-binom"><span class="math display">\[
\big(P(0),\dots,P(5)\big)=(0.07776,\ 0.25920,\ 0.34560,\ 0.23040,\ 0.07680,\ 0.01024),
\tag{21.20}\]</span></span> with mean <span class="math inline">\(n\theta_\bullet=2.0\)</span> and variance <span class="math inline">\(n\theta_\bullet(1-\theta_\bullet)=5(0.4)(0.6)=1.20\)</span>.</p>
<p><strong>Step 3: the exact Poisson binomial (route two).</strong> Conditional on the five distinct profiles, the count is <span class="math inline">\(\mathrm{PoBin}(\mathbf p)\)</span>, whose mass function we obtain as the coefficients of the generating polynomial <a href="#eq-pobin-pgf" class="quarto-xref">Equation&nbsp;<span>21.8</span></a>, <span id="eq-ex-pgf"><span class="math display">\[
G(z)=(0.9+0.1z)(0.7+0.3z)(0.6+0.4z)(0.5+0.5z)(0.3+0.7z).
\tag{21.21}\]</span></span> Multiplying the factors in turn, <span class="math display">\[
\begin{aligned}
(0.9+0.1z)(0.7+0.3z)&amp;=0.63+0.34z+0.03z^2,\\
{}\times(0.6+0.4z)&amp;=0.378+0.456z+0.154z^2+0.012z^3,\\
{}\times(0.5+0.5z)&amp;=0.189+0.417z+0.305z^2+0.083z^3+0.006z^4,\\
{}\times(0.3+0.7z)&amp;=0.0567+0.2574z+0.3834z^2+0.2384z^3+0.0599z^4+0.0042z^5,
\end{aligned}
\]</span> so the exact aggregate count law is <span id="eq-ex-pobin"><span class="math display">\[
\big(P(0),\dots,P(5)\big)=(0.0567,\ 0.2574,\ 0.3834,\ 0.2384,\ 0.0599,\ 0.0042).
\tag{21.22}\]</span></span> As a check the coefficients sum to <span class="math inline">\(1\)</span>; the mean is <span class="math inline">\(\sum_y y\,P(y)=2.0=\lambda\)</span> and the variance is <span class="math inline">\(\sum_y y^2 P(y)-2.0^2=5.0-4.0=1.00=\lambda-\nu\)</span>, matching <a href="#thm-poisson-binomial-pgf" class="quarto-xref">Theorem&nbsp;<span>21.2</span></a>. The distribution is mildly right-skewed, with third central moment <span class="math inline">\(\sum_i p_i(1-p_i)(1-2p_i)=0.12&gt;0\)</span>, reflecting the spread of the underlying risks; this skew is one feature the two-moment surrogates of Steps 4 and 5 cannot reproduce.</p>
<p><strong>Step 4: the adjusted binomial (route three).</strong> By <a href="#eq-adjbin-solution" class="quarto-xref">Equation&nbsp;<span>21.18</span></a>, <span class="math display">\[
\pi^{*}=\frac{\nu}{\lambda}=\frac{1.0}{2.0}=0.5,
\qquad
N^{*}=\frac{\lambda^2}{\nu}=\frac{4.0}{1.0}=4 ,
\]</span> an integer here by design, so the adjusted aggregate law is <span class="math inline">\(\mathrm{Bin}(4,0.5)\)</span> with <span class="math inline">\(P(y)=\binom{4}{y}(0.5)^{4}=\binom{4}{y}/16\)</span>, <span id="eq-ex-adjbin"><span class="math display">\[
\big(P(0),\dots,P(4)\big)=(0.0625,\ 0.25,\ 0.375,\ 0.25,\ 0.0625),
\qquad P(5)=0 .
\tag{21.23}\]</span></span> Its mean is <span class="math inline">\(N^{*}\pi^{*}=2.0\)</span> and variance <span class="math inline">\(N^{*}\pi^{*}(1-\pi^{*})=4(0.5)(0.5)=1.00\)</span>, matching the exact Poisson binomial mean and variance by construction. Note <span class="math inline">\(N^{*}=4&lt;5=n\)</span>, the Cauchy-Schwarz deflation of <a href="#thm-adjusted-binomial" class="quarto-xref">Theorem&nbsp;<span>21.4</span></a>; the adjusted binomial cannot produce the count <span class="math inline">\(5\)</span>, whereas the exact Poisson binomial assigns it probability <span class="math inline">\(0.0042\)</span>.</p>
<p><strong>Step 5: the Le Cam Poisson, for contrast.</strong> The matched Poisson is <span class="math inline">\(\mathrm{Poi}(\lambda)=\mathrm{Poi}(2)\)</span>, with <span class="math inline">\(P(y)=e^{-2}2^{y}/y!\)</span>, <span id="eq-ex-poisson"><span class="math display">\[
\big(P(0),\dots,P(5)\big)=(0.1353,\ 0.2707,\ 0.2707,\ 0.1804,\ 0.0902,\ 0.0361),\ \dots
\tag{21.24}\]</span></span> its support unbounded. Its mean is <span class="math inline">\(2.0\)</span> but its variance is <span class="math inline">\(\lambda=2.0\)</span>, far larger than the true <span class="math inline">\(1.00\)</span>: the Poisson cannot capture the underdispersion of a binary count.</p>
<p><a href="#tbl-worked-comparison" class="quarto-xref">Table&nbsp;<span>21.3</span></a> places the four laws side by side before we read off the reported count.</p>
<div id="tbl-worked-comparison" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-worked-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;21.3: The aggregate-count likelihood under the four laws of <a href="#exm-aggregate-binomial" class="quarto-xref">Example&nbsp;<span>21.5</span></a> (five profiles, risks <span class="math inline">\(\mathbf p=(0.1,0.3,0.4,0.5,0.7)\)</span>). The two-moment surrogates match the exact mean and variance (<span class="math inline">\(2.00\)</span> and <span class="math inline">\(1.00\)</span>); the integrated binomial matches the mean but inflates the variance to <span class="math inline">\(1.20\)</span>; the Le Cam Poisson matches only the mean, and with variance <span class="math inline">\(2.00\)</span> and unbounded support (the <span class="math inline">\(y\ge 6\)</span> tail carries the remaining <span class="math inline">\(0.0166\)</span>) is visibly the worst fit.
</figcaption>
<div aria-describedby="tbl-worked-comparison-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th><span class="math inline">\(y\)</span></th>
<th>exact PoBin</th>
<th>adjusted <span class="math inline">\(\mathrm{Bin}(4,0.5)\)</span></th>
<th>integrated <span class="math inline">\(\mathrm{Bin}(5,0.4)\)</span></th>
<th>Le Cam <span class="math inline">\(\mathrm{Poi}(2)\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(0.0567\)</span></td>
<td><span class="math inline">\(0.0625\)</span></td>
<td><span class="math inline">\(0.0778\)</span></td>
<td><span class="math inline">\(0.1353\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(1\)</span></td>
<td><span class="math inline">\(0.2574\)</span></td>
<td><span class="math inline">\(0.2500\)</span></td>
<td><span class="math inline">\(0.2592\)</span></td>
<td><span class="math inline">\(0.2707\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(2\)</span></td>
<td><span class="math inline">\(0.3834\)</span></td>
<td><span class="math inline">\(0.3750\)</span></td>
<td><span class="math inline">\(0.3456\)</span></td>
<td><span class="math inline">\(0.2707\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(3\)</span></td>
<td><span class="math inline">\(0.2384\)</span></td>
<td><span class="math inline">\(0.2500\)</span></td>
<td><span class="math inline">\(0.2304\)</span></td>
<td><span class="math inline">\(0.1804\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(4\)</span></td>
<td><span class="math inline">\(0.0599\)</span></td>
<td><span class="math inline">\(0.0625\)</span></td>
<td><span class="math inline">\(0.0768\)</span></td>
<td><span class="math inline">\(0.0902\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(5\)</span></td>
<td><span class="math inline">\(0.0042\)</span></td>
<td><span class="math inline">\(0\)</span></td>
<td><span class="math inline">\(0.0102\)</span></td>
<td><span class="math inline">\(0.0361\)</span></td>
</tr>
<tr class="odd">
<td>mean</td>
<td><span class="math inline">\(2.00\)</span></td>
<td><span class="math inline">\(2.00\)</span></td>
<td><span class="math inline">\(2.00\)</span></td>
<td><span class="math inline">\(2.00\)</span></td>
</tr>
<tr class="even">
<td>variance</td>
<td><span class="math inline">\(1.00\)</span></td>
<td><span class="math inline">\(1.00\)</span></td>
<td><span class="math inline">\(1.20\)</span></td>
<td><span class="math inline">\(2.00\)</span></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><strong>Step 6: compare the likelihoods.</strong> Suppose the arm reports <span class="math inline">\(y_\bullet=2\)</span> responders, the modal count. The aggregate likelihood contribution under each model is the value at <span class="math inline">\(y=2\)</span>: <span class="math display">\[
\underbrace{0.3834}_{\text{exact PoBin}},\quad
\underbrace{0.375}_{\text{adjusted }\mathrm{Bin}(4,0.5)},\quad
\underbrace{0.3456}_{\text{integrated }\mathrm{Bin}(5,0.4)},\quad
\underbrace{0.2707}_{\text{Le Cam }\mathrm{Poi}(2)} .
\]</span> The adjusted binomial is within <span class="math inline">\(0.0084\)</span> of the exact value, the integrated binomial within <span class="math inline">\(0.0378\)</span>, and the Le Cam Poisson off by <span class="math inline">\(0.1127\)</span>. The whole-distribution discrepancies tell the same story through the total-variation distance <a href="#eq-tv-three-forms" class="quarto-xref">Equation&nbsp;<span>21.12</span></a>: <span class="math display">\[
\big\|\mathrm{PoBin}-\mathrm{Bin}(4,0.5)\big\|_{\mathrm{TV}}=0.0200,
\qquad
\big\|\mathrm{PoBin}-\mathrm{Poi}(2)\big\|_{\mathrm{TV}}=0.1707 .
\]</span> The Le Cam bound <a href="#eq-lecam-bound" class="quarto-xref">Equation&nbsp;<span>21.14</span></a> for this arm is <span class="math inline">\(\sum_i p_i^2=\nu=1.00\)</span>, and the Barbour-Hall refinement is <span class="math inline">\(\min(1,\lambda^{-1})\nu=0.5\)</span>; both are correct (the actual distance <span class="math inline">\(0.1707\)</span> is well below them) but far too loose to be useful, exactly the moderate-risk regime where the Poisson approximation is poor.</p>
<p><strong>Step 7: reconcile the two binomials.</strong> The integrated binomial <a href="#eq-ex-binom" class="quarto-xref">Equation&nbsp;<span>21.20</span></a> and the exact Poisson binomial <a href="#eq-ex-pobin" class="quarto-xref">Equation&nbsp;<span>21.22</span></a> share the mean <span class="math inline">\(2.0\)</span> but differ in variance, <span class="math inline">\(1.20\)</span> against <span class="math inline">\(1.00\)</span>. The difference is <span class="math display">\[
n\theta_\bullet(1-\theta_\bullet)-(\lambda-\nu)=\nu-\frac{\lambda^2}{n}=1.00-\frac{4.0}{5}=0.20
=n\,s_p^2,
\]</span> the population variance of the five risks times the sample size, <span class="math inline">\(s_p^2=\tfrac1n\nu-\bar p^2=0.20-0.16=0.04\)</span>. This is the binary shadow of the mixed-Poisson overdispersion <a href="#eq-poisson-agg-moments" class="quarto-xref">Equation&nbsp;<span>21.5</span></a>: randomizing which profile a patient occupies, as the integrated binomial does, adds variance <span class="math inline">\(n\,s_p^2\)</span> over the conditional law that fixes one patient at each profile. The adjusted binomial <a href="#eq-ex-adjbin" class="quarto-xref">Equation&nbsp;<span>21.23</span></a> tracks the <em>conditional</em> Poisson binomial (right variance <span class="math inline">\(1.00\)</span>), while the integrated binomial <a href="#eq-ex-binom" class="quarto-xref">Equation&nbsp;<span>21.20</span></a> is the exact <em>marginal</em> law (variance <span class="math inline">\(1.20\)</span>); both are legitimate answers to slightly different questions, and the worked numbers make the distinction concrete. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
<div class="proof remark">
<p><span class="proof-title"><em>Remark</em>. </span><strong>Which likelihood to report.</strong> For a genuine exchangeable sample of patients, the integrated binomial <a href="#eq-ex-binom" class="quarto-xref">Equation&nbsp;<span>21.20</span></a> is exact and is the default ML-NMR choice (<a href="#prp-marginal-binomial" class="quarto-xref">Proposition&nbsp;<span>21.1</span></a>, <span class="citation" data-cites="phillippo2020mlnmr">Phillippo et al. (<a href="../../references.html#ref-phillippo2020mlnmr" role="doc-biblioref">2020</a>)</span>). When one instead conditions on a fixed set of representative profiles, as the deterministic integration nodes of Chapter 22 are, the conditional Poisson binomial is the target and the adjusted binomial <a href="#eq-ex-adjbin" class="quarto-xref">Equation&nbsp;<span>21.23</span></a> is its faithful two-moment surrogate. The Le Cam Poisson is never competitive at these risks; its value is theoretical, as the sharp total-variation statement of <a href="#thm-le-cam-tv" class="quarto-xref">Theorem&nbsp;<span>21.3</span></a> and as the bridge to the Poisson limit of Chapter 4. The single discipline that matters in practice is to match the variance, which both the integrated and the adjusted binomial do for their respective targets and the Poisson does not. <span class="math inline">\(\blacktriangleleft\)</span></p>
</div>
</section>
<section id="sec-discrete-notes" class="level2" data-number="21.9">
<h2 data-number="21.9" class="anchored" data-anchor-id="sec-discrete-notes"><span class="header-section-number">21.9</span> Notes and references</h2>
<p>The aggregation principle of multilevel network meta-regression, and the integral form of the aggregate mean that underlies the integrated binomial likelihood <a href="#eq-integrated-binomial" class="quarto-xref">Equation&nbsp;<span>21.1</span></a>, are due to <span class="citation" data-cites="phillippo2020mlnmr">Phillippo et al. (<a href="../../references.html#ref-phillippo2020mlnmr" role="doc-biblioref">2020</a>)</span> and the thesis <span class="citation" data-cites="phillippo2019thesis">Phillippo (<a href="../../references.html#ref-phillippo2019thesis" role="doc-biblioref">2019</a>)</span>; this chapter develops the discrete-outcome likelihoods that the principle requires, the material of the catalogue results H.8 to H.11. The closure of the Poisson family under convolution (<a href="#lem-poisson-convolution" class="quarto-xref">Lemma&nbsp;<span>21.1</span></a>) and the resulting exact conditional Poisson aggregate are classical; the moment generating function proof rests on the uniqueness and product theorems of Chapter 4 (<a href="../part1/04-probability.html#thm-mgf-uniqueness" class="quarto-xref">Theorem&nbsp;<span>4.11</span></a>, <a href="../part1/04-probability.html#thm-mgf-sum" class="quarto-xref">Theorem&nbsp;<span>4.12</span></a>). The corrected statement that the <em>marginalized</em> aggregate count is a mixed Poisson, overdispersed by <span class="math inline">\(n\sigma_W^2\)</span> rather than itself Poisson (<a href="#thm-poisson-aggregate" class="quarto-xref">Theorem&nbsp;<span>21.1</span></a>), follows from the law of total variance; the closed-form relative overdispersion <span class="math inline">\(e^{\boldsymbol\beta_{\mathrm{tot}}^\top\boldsymbol\Sigma_j\boldsymbol\beta_{\mathrm{tot}}}-1\)</span> under Gaussian covariates uses the log-link aggregate identity of Chapter 20 (<a href="20-mlnmr-aggregation.html#thm-log-link-mgf" class="quarto-xref">Theorem&nbsp;<span>20.4</span></a>). The negative-binomial remedy for overdispersed counts is the count-data analogue of a study-level random effect (<a href="../part1/08-hierarchical-bayes.html#def-random-effects" class="quarto-xref">Definition&nbsp;<span>8.3</span></a>) and is standard in the generalized linear model literature (<span class="citation" data-cites="mccullagh1989glm">McCullagh and Nelder (<a href="../../references.html#ref-mccullagh1989glm" role="doc-biblioref">1989</a>)</span>).</p>
<p>The Poisson binomial distribution and its generating function (<a href="../part1/04-probability.html#def-poisson-binomial" class="quarto-xref">Definition&nbsp;<span>4.11</span></a>, <a href="#thm-poisson-binomial-pgf" class="quarto-xref">Theorem&nbsp;<span>21.2</span></a>) are textbook once the probability generating function is in hand; the chapter introduces the generating function (<a href="#def-pgf" class="quarto-xref">Definition&nbsp;<span>21.1</span></a>) as the integer-valued counterpart of the moment generating function of Chapter 4 (<a href="../part1/04-probability.html#def-mgf" class="quarto-xref">Definition&nbsp;<span>4.7</span></a>). The intractability of the exact mass function, with its <span class="math inline">\(\binom{n}{y}\)</span> subset terms, motivates the two approximations. Le Cam’s total-variation bound (<a href="#thm-le-cam-tv" class="quarto-xref">Theorem&nbsp;<span>21.3</span></a>) is from <span class="citation" data-cites="lecam1960">Le Cam (<a href="../../references.html#ref-lecam1960" role="doc-biblioref">1960</a>)</span>; the coupling proof given here is self-contained, building on the coupling inequality (<a href="#lem-coupling-inequality" class="quarto-xref">Lemma&nbsp;<span>21.3</span></a>) and an explicit single-pair coupling of a Bernoulli with a Poisson, and uses the author’s own <a href="#lem-poisson-convolution" class="quarto-xref">Lemma&nbsp;<span>21.1</span></a> to identify the summed Poisson coupling. The sharper bound <span class="math inline">\(\min(1,\lambda^{-1})\sum_i p_i^2\)</span>, with a matching lower bound establishing that the order is correct, is due to Barbour and Hall (1984) and is most cleanly obtained by Stein’s method for Poisson approximation, the operator technique introduced by Chen (1975) and developed at length by Barbour, Holst, and Janson (1992); these three sources are not in the book’s bibliography and are recorded in the work log as proposed additions. The adjusted two-parameter binomial obtained by moment matching (<a href="#thm-adjusted-binomial" class="quarto-xref">Theorem&nbsp;<span>21.4</span></a>) is the binary aggregate likelihood of <span class="citation" data-cites="phillippo2020mlnmr">Phillippo et al. (<a href="../../references.html#ref-phillippo2020mlnmr" role="doc-biblioref">2020</a>)</span> and <span class="citation" data-cites="phillippo2019thesis">Phillippo (<a href="../../references.html#ref-phillippo2019thesis" role="doc-biblioref">2019</a>)</span> (Equation 4.6 of the thesis); its effective sample size <span class="math inline">\(N^{*}=(\sum_i p_i)^2/\sum_i p_i^2\)</span> is the same Cauchy-Schwarz functional as the weighting effective sample size of Chapter 18 (<a href="../part4/18-maic.html#thm-maic-ess-bound" class="quarto-xref">Theorem&nbsp;<span>18.6</span></a>), a pleasing recurrence of the same inequality in a different guise.</p>
<p>The forward connections are to the rest of Part V. The aggregate means <span class="math inline">\(\theta_{\bullet jk}\)</span> that feed all of these likelihoods are themselves integrals that, for the logit and log links, have no elementary closed form (<a href="20-mlnmr-aggregation.html#thm-logit-no-closed-form" class="quarto-xref">Theorem&nbsp;<span>20.5</span></a>) and must be evaluated by the quasi-Monte Carlo machinery of Chapter 22 (<a href="22-mlnmr-integration.html#thm-koksma-hlawka" class="quarto-xref">Theorem&nbsp;<span>22.3</span></a>, <a href="22-mlnmr-integration.html#thm-mc-rmse" class="quarto-xref">Theorem&nbsp;<span>22.2</span></a>); the discrete likelihoods of this chapter sit on top of that integration. The likelihoods are assembled into the target-population estimands of Chapter 23 (<a href="23-mlnmr-estimands.html#thm-target-population-integral" class="quarto-xref">Theorem&nbsp;<span>23.1</span></a>) and fitted by the Bayesian computation of Chapter 24. The general-likelihood formulation of <span class="citation" data-cites="phillippo2025general">Phillippo et al. (<a href="../../references.html#ref-phillippo2025general" role="doc-biblioref">2025</a>)</span> (Chapter 25, <a href="25-general-likelihoods.html#thm-general-likelihood-mlnmr" class="quarto-xref">Theorem&nbsp;<span>25.7</span></a>) places the binomial, Poisson, and their adjusted and overdispersed variants in a single framework, of which the count and binary cases treated here are the leading instances.</p>
<p>No result in this chapter has a counterpart in the companion Coq development: the <code>ITC_Coq</code> <code>theories</code> directory formalizes the causal and weighting core of Parts II to IV but not the discrete-outcome approximation theory of Part V, which is computational and analytic. Accordingly none of <a href="#lem-poisson-convolution" class="quarto-xref">Lemma&nbsp;<span>21.1</span></a>, <a href="#thm-poisson-aggregate" class="quarto-xref">Theorem&nbsp;<span>21.1</span></a>, <a href="#thm-poisson-binomial-pgf" class="quarto-xref">Theorem&nbsp;<span>21.2</span></a>, <a href="#thm-le-cam-tv" class="quarto-xref">Theorem&nbsp;<span>21.3</span></a>, or <a href="#thm-adjusted-binomial" class="quarto-xref">Theorem&nbsp;<span>21.4</span></a> carries a machine-checked tag; their proofs are pen-and-paper and complete as given.</p>
</section>
<section id="sec-discrete-exercises" class="level2" data-number="21.10">
<h2 data-number="21.10" class="anchored" data-anchor-id="sec-discrete-exercises"><span class="header-section-number">21.10</span> Exercises</h2>
<p>A <span class="math inline">\(\star\)</span> marks an exercise with a full worked solution in Appendix F; here the starred exercises are <a href="#exr-lecam-coupling" class="quarto-xref">Exercise&nbsp;<span>21.6</span></a> and <a href="#exr-adjbin-thirdmoment" class="quarto-xref">Exercise&nbsp;<span>21.8</span></a>. The first three exercises are warm-ups (interpretation and likelihood selection) to fix the ideas before the computational and proof exercises that follow.</p>
<div id="exr-why-not-binomial" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 21.1</strong></span> <strong>Why unequal risks are not binomial (in words).</strong> In one or two sentences, explain to a colleague why the total number of responders among five patients with response probabilities <span class="math inline">\(0.1,0.3,0.4,0.5,0.7\)</span> is <em>not</em> distributed as <span class="math inline">\(\mathrm{Bin}(5,0.4)\)</span>, even though the average risk is <span class="math inline">\(0.4\)</span>. Using <a href="#exm-two-bernoulli-pgf" class="quarto-xref">Example&nbsp;<span>21.4</span></a> as a guide, say what breaks in the assumption that every patient shares one common success probability, and name the distribution that is correct.</p>
</div>
<div id="exr-choose-likelihood" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 21.2</strong></span> <strong>Choosing the aggregate likelihood.</strong> For each scenario, name the aggregate law you would use from <a href="#tbl-aggregate-laws" class="quarto-xref">Table&nbsp;<span>21.1</span></a> (integrated binomial, adjusted binomial, exact Poisson binomial, Le Cam Poisson, or a negative binomial) and justify the choice in one sentence. (a) A binary responder arm whose patients are an exchangeable random sample from a covariate distribution you can integrate over. (b) A binary safety endpoint (a rare adverse event, average risk about <span class="math inline">\(2\%\)</span>) summarized at a handful of fixed integration nodes. (c) A binary responder arm represented by fixed integration nodes at moderate risks (<span class="math inline">\(0.2\)</span> to <span class="math inline">\(0.7\)</span>). (d) A count outcome (hospitalizations) with strong effect modifiers, where a plain Poisson badly understates the variance.</p>
</div>
<div id="exr-two-patient-warmup" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 21.3</strong></span> <strong>Conditional and marginal by hand.</strong> Two profiles have response probabilities <span class="math inline">\(0.2\)</span> and <span class="math inline">\(0.6\)</span>, equally prevalent, and the arm has <span class="math inline">\(n=2\)</span>. (a) Compute the conditional law of the count with one patient fixed at each profile (its three probabilities, mean, and variance). (b) Compute the marginal law when each patient is an independent draw from the two-profile population, and recognize it as a binomial. (c) Confirm the two laws share a mean but that the marginal variance exceeds the conditional variance by <span class="math inline">\(n\,s_p^2\)</span>, and report <span class="math inline">\(s_p^2\)</span>. Compare with <a href="#exm-two-patient-conditional" class="quarto-xref">Example&nbsp;<span>21.2</span></a>.</p>
</div>
<div id="exr-poisson-twopoint" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 21.4</strong></span> <strong>A count aggregate with a two-point covariate.</strong> A Poisson-outcome AgD arm has <span class="math inline">\(n=20\)</span> patients and a single binary effect modifier <span class="math inline">\(x\in\{0,1\}\)</span> with <span class="math inline">\(P(x=1)=0.5\)</span> in the study, and log-link linear predictor <span class="math inline">\(\eta(x)=\log 2+x\log 2\)</span>, so that the conditional rate is <span class="math inline">\(W=e^{\eta(x)}\)</span>. Compute the two possible rates, the aggregate mean rate <span class="math inline">\(\theta_\bullet=\mathbb{E}[W]\)</span>, the rate variance <span class="math inline">\(\sigma_W^2\)</span>, the marginal mean <span class="math inline">\(\mathbb{E}[Y_\bullet]\)</span> and variance <span class="math inline">\(\operatorname{Var}(Y_\bullet)\)</span> from <a href="#eq-poisson-agg-moments" class="quarto-xref">Equation&nbsp;<span>21.5</span></a>, and the dispersion index <span class="math inline">\(\operatorname{Var}(Y_\bullet)/\mathbb{E}[Y_\bullet]\)</span>. By how many percent does ignoring the overdispersion understate the variance?</p>
</div>
<div id="exr-pobin-pgf-compute" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 21.5</strong></span> <strong>Poisson binomial by generating function.</strong> For risks <span class="math inline">\(\mathbf p=(0.2,0.5,0.8)\)</span>, write the generating polynomial <a href="#eq-pobin-pgf" class="quarto-xref">Equation&nbsp;<span>21.8</span></a>, expand it to obtain the full mass function, and verify the mean and variance against <a href="#eq-pobin-moments" class="quarto-xref">Equation&nbsp;<span>21.10</span></a>. Compare the mass function to that of the binomial <span class="math inline">\(\mathrm{Bin}(3,\bar p)\)</span> with the same mean (<span class="math inline">\(\bar p=0.5\)</span>): which has the larger variance, and why does the remark after <a href="#thm-poisson-binomial-pgf" class="quarto-xref">Theorem&nbsp;<span>21.2</span></a> predict this?</p>
</div>
<div id="exr-lecam-coupling" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 21.6</strong></span> <strong>(<span class="math inline">\(\star\)</span>) The coupling, the bound, and its sharpness.</strong> (a) Verify directly from <a href="#eq-lecam-pair" class="quarto-xref">Equation&nbsp;<span>21.15</span></a> that the single-pair coupling has Bernoulli and Poisson marginals and disagreement probability <span class="math inline">\(p(1-e^{-p})\)</span>. (b) Prove the coupling inequality <a href="#eq-coupling-ineq" class="quarto-xref">Equation&nbsp;<span>21.13</span></a> and deduce <a href="#eq-lecam-bound" class="quarto-xref">Equation&nbsp;<span>21.14</span></a> for a general risk vector. (c) For the equal-risk case <span class="math inline">\(p_i\equiv p\)</span>, show the bound becomes <span class="math inline">\(\|\mathrm{Bin}(n,p)-\mathrm{Poi}(np)\|_{\mathrm{TV}}
\le np^2\)</span> and relate this to the Poisson limit theorem <a href="../part1/04-probability.html#thm-poisson-limit" class="quarto-xref">Theorem&nbsp;<span>4.13</span></a>. (d) Using a second-order expansion <span class="math inline">\(1-e^{-p}=p-\tfrac12 p^2+O(p^3)\)</span>, argue that the per-pair disagreement is <span class="math inline">\(p^2-\tfrac12 p^3+O(p^4)\)</span>, so the bound <span class="math inline">\(\sum_i p_i^2\)</span> is tight to leading order in small risks.</p>
</div>
<div id="exr-adjbin-moments" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 21.7</strong></span> <strong>Computing and reading the adjusted binomial.</strong> For <span class="math inline">\(\mathbf p=(0.2,0.4,0.6,0.8)\)</span> compute <span class="math inline">\(\lambda\)</span>, <span class="math inline">\(\nu\)</span>, <span class="math inline">\(\pi^{*}\)</span>, and <span class="math inline">\(N^{*}\)</span> from <a href="#eq-adjbin-solution" class="quarto-xref">Equation&nbsp;<span>21.18</span></a>, confirm <span class="math inline">\(N^{*}\le n\)</span>, and evaluate the adjusted-binomial mass at the count <span class="math inline">\(y=2\)</span> using the Gamma-function form of the binomial mass when <span class="math inline">\(N^{*}\)</span> is not an integer. Compare with the exact Poisson binomial mass at <span class="math inline">\(y=2\)</span> (compute it from the generating polynomial), and report the total-variation distance between the exact and adjusted laws.</p>
</div>
<div id="exr-adjbin-thirdmoment" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 21.8</strong></span> <strong>(<span class="math inline">\(\star\)</span>) Moment matching stops at two.</strong> The third central moment of <span class="math inline">\(\mathrm{Bin}(N,\pi)\)</span> is <span class="math inline">\(N\pi(1-\pi)(1-2\pi)\)</span>, and that of <span class="math inline">\(\mathrm{PoBin}(\mathbf p)\)</span> is <span class="math inline">\(\sum_i p_i(1-p_i)(1-2p_i)\)</span>. (a) Prove the Poisson binomial formula from the generating function <a href="#eq-pobin-pgf" class="quarto-xref">Equation&nbsp;<span>21.8</span></a> or from the independence of the Bernoulli summands. (b) For the risk vector <span class="math inline">\(\mathbf p=(0.1,0.3,0.4,0.5,0.7)\)</span> of <a href="#exm-aggregate-binomial" class="quarto-xref">Example&nbsp;<span>21.5</span></a>, compute the Poisson binomial third central moment and the adjusted-binomial third central moment from the matched parameters <span class="math inline">\((N^{*},\pi^{*})=(4,0.5)\)</span>, and show they differ: the adjusted binomial is symmetric so its third central moment is zero, whereas the Poisson binomial has third central moment <span class="math inline">\(\sum_i p_i(1-p_i)(1-2p_i)=0.12&gt;0\)</span>, a right skew the surrogate misses. Conclude that no choice of <span class="math inline">\((N,\pi)\)</span> can match three moments of a generic Poisson binomial, so the adjusted binomial is genuinely a two-moment surrogate, consistent with the remark after <a href="#thm-adjusted-binomial" class="quarto-xref">Theorem&nbsp;<span>21.4</span></a> that no total-variation guarantee is available.</p>
</div>
<div id="exr-overdispersion-gaussian" class="theorem exercise">
<p><span class="theorem-title"><strong>Exercise 21.9</strong></span> <strong>Overdispersion under Gaussian covariates.</strong> A Poisson-outcome arm has <span class="math inline">\(\theta_\bullet=3\)</span> events per patient on average and a single continuous covariate with total slope <span class="math inline">\(\beta_{\mathrm{tot}}=0.5\)</span> and within-study standard deviation <span class="math inline">\(\sigma=0.8\)</span>, so <span class="math inline">\(s^2=\beta_{\mathrm{tot}}^2\sigma^2\)</span>. Using <a href="#eq-poisson-agg-overdisp" class="quarto-xref">Equation&nbsp;<span>21.6</span></a>, compute the squared coefficient of variation of the rate, the per-patient excess variance <span class="math inline">\(\sigma_W^2\)</span>, and the dispersion index <span class="math inline">\(\operatorname{Var}(Y_\bullet)/\mathbb{E}[Y_\bullet]\)</span> for <span class="math inline">\(n=50\)</span> patients. State the value of <span class="math inline">\(s^2\)</span> below which the dispersion index stays under <span class="math inline">\(1.05\)</span>, and interpret it as a tolerance on the effect-modifier strength.</p>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-lecam1960" class="csl-entry" role="listitem">
Le Cam, Lucien. 1960. <span>“An Approximation Theorem for the Poisson Binomial Distribution.”</span> <em>Pacific Journal of Mathematics</em> 10 (4): 1181–97.
</div>
<div id="ref-mccullagh1989glm" class="csl-entry" role="listitem">
McCullagh, Peter, and John A. Nelder. 1989. <em>Generalized Linear Models</em>. 2nd ed. Chapman &amp; Hall/CRC.
</div>
<div id="ref-phillippo2019thesis" class="csl-entry" role="listitem">
Phillippo, David Mark. 2019. <span>“Calibration of Treatment Effects in Network Meta-Analysis Using Individual Patient Data.”</span> PhD thesis, University of Bristol.
</div>
<div id="ref-phillippo2020mlnmr" class="csl-entry" role="listitem">
Phillippo, David M., Sofia Dias, A. E. Ades, et al. 2020. <span>“Multilevel Network Meta-Regression for Population-Adjusted Treatment Comparisons.”</span> <em>Journal of the Royal Statistical Society: Series A</em> 183 (3): 1189–210. <a href="https://doi.org/10.1111/rssa.12579">https://doi.org/10.1111/rssa.12579</a>.
</div>
<div id="ref-phillippo2025general" class="csl-entry" role="listitem">
Phillippo, David M., Sofia Dias, A. E. Ades, and Nicky J. Welton. 2025. <span>“Multilevel Network Meta-Regression for General Likelihoods.”</span> <em>Journal of the Royal Statistical Society: Series A</em>, ahead of print. <a href="https://doi.org/10.1093/jrsssa/qnaf169">https://doi.org/10.1093/jrsssa/qnaf169</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/choxos\.github\.io\/Mathematics-of-ITC\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/part5/20-mlnmr-aggregation.html" class="pagination-link" aria-label="Multilevel Network Meta-Regression I: The Aggregation Principle">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Multilevel Network Meta-Regression I: The Aggregation Principle</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/part5/22-mlnmr-integration.html" class="pagination-link" aria-label="Multilevel Network Meta-Regression III: Numerical Integration Theory">
        <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Multilevel Network Meta-Regression III: Numerical Integration Theory</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>